### PR TITLE
Disable tagged PDF export when using the --pages option

### LINKED ISSUE #7047: Panic when exporting non-existent PDF pages
### Description

Compiling a non-empty document with `--pages=n` where `n` is a page number that doesn't exist produces a panic in typst-pdf with the following error message:

```
thread 'main' panicked at crates\typst-pdf\src\tags\tree\mod.rs:72:9:
assertion `left == right` failed: tree traversal didn't complete properly
```

Minimal reproduction:

```typ
// panic.typ
Foo
```

```sh
typst compile panic.typ --pages=2
```

Tested on 8ace67d9.

### Reproduction URL

_No response_

### Operating system

Windows

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by saecki**
Fixes #7047.

This disables tagged PDF export when using the `--pages` option.
Additionally a warning is emitted when `--no-pdf-tags` isn't used.
And a hint is added to the error when an accessible PDF standard is specified.

Hints from application level errors previously weren't printed.

### CODE REVIEW

File: crates/typst-cli/src/compile.rs [hunk 1]
```diff
@@ -134,7 +138,12 @@ impl CompileConfig {
             PageRanges::new(export_ranges.iter().map(|r| r.0.clone()).collect())
         });
 
-        if args.no_pdf_tags {
+        let tagged = !args.no_pdf_tags && pages.is_none();
+        if pages.is_some() && !args.no_pdf_tags {
+            warnings.push("using --pages implies --no-pdf-tags");
```
Comment (reknih) [inline crates/typst-cli/src/compile.rs]:
```suggestion
            warnings.push(
                SourceDiagnostic::warning(
                    Span::detached(),
                    "using --pages implies --no-pdf-tags",
                )
                .with_hints([
                    "the resulting PDF will be inaccessible".into(),
                    "add --no-pdf-tags to silence this warning".into(),
                ]),
            );
```

**Comment by reknih** [comment]
Also, this needs to check for the PDF target:

```
cargo run -- compile --pages 1 -f png tests/suite/playground.typ
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/typst c --pages 1 -f png tests/suite/playground.typ`

warning: using --pages implies --no-pdf-tags
 = hint: the resulting PDF will be inaccessible
 = hint: add --no-pdf-tags to silence this warning
```

File: crates/typst-cli/src/compile.rs [hunk 2]
```diff
@@ -187,8 +192,10 @@ impl CompileConfig {
         {
             deps = Some(Output::Path(path.clone()));
             deps_format = DepsFormat::Make;
-            warnings
-                .push("--make-deps is deprecated, use --deps and --deps-format instead");
+            warnings.push(
+                HintedString::from("--make-deps is deprecated")
+                    .with_hint("use --deps and --deps-format instead"),
+            );
```
Comment (laurmaedje) [inline crates/typst-cli/src/compile.rs:197]: I discussed that with Martin and I think I'd like to keep the previous version for consistency with all of our other deprecation warnings

Comment (saecki) [reply crates/typst-cli/src/compile.rs:197]: Ok, so just keep it all as one warning, no hint right?
