### PR TITLE
Do not create a block frame for out-of-flow items only

### LINKED ISSUE #2297: Elements with no content can force a breakable block to create an empty frame
### Description

If a block has its `breakable` property set to `true`, it may be broken across multiple pages in what are called “frames”. When an element in a block is too big to fit on the current page, it creates a new frame on the next one and the block continues there. If the first frame of a block is empty (typically, because the first element of the block was too big to fit on the first page), it is not displayed (unless there is no other frame).

https://github.com/typst/typst/blob/cf9bde3245817e068c8253070e7a94dcc05369fb/crates/typst-library/src/layout/container.rs#L423-L426

However, if the first frame of a block contains elements that have no visible content (like a counter update), it is still displayed, even though it has no visible content.

This issue should not be too hard to fix, as a similar problem was already solved in #1929, although there is something more to this one: out-of-flow elements (typically, [`place`](https://typst.app/docs/reference/layout/place/)) should be treated as “basically empty”, and they may also have to move accross frames. Indeed, if the element that causes the first frame to be displayed is an out-of-flow element, I think it is safe to assume you would want it to (1) not cause the first frame to be displayed, and (2) be laid out as part of the first displayed frame.

### Reproduction URL

https://typst.app/project/rKKGxCfjnle00zlOLl1J4R

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by MDLC01**
Fixes #2297

This PR makes it so that, when a breakable block is broken into multiple frames, a frame containing only out-of-flow items (which correspond to `place` elements, counter updates, etc.) will move its items to the next frame if there is one.

***Please review this carefully!*** I was not familiar with this part of the codebase when I started working on that, so please make sure I did not write anything stupid. All tests pass, so it should be ok, but there are still some things I'm not fully confident about (see comments). In particular, because this fix is implemented by modifying the way `FlowElem` is laid out, I think it may affect other things (although I could not think of any).

### CODE REVIEW

File: crates/typst-library/src/layout/flow.rs [hunk 1]
```diff
@@ -436,6 +440,24 @@ impl<'a> FlowLayouter<'a> {
...
+        }
+
+        if !self.items.is_empty() && self.items.iter().all(|item| {
+            match item {
+                FlowItem::Placed {float: false, ..} => true,
+                FlowItem::Frame {frame, ..} => frame.size().is_zero(),
+                _ => false,
+            }
+        }) {
+            self.last_frame_only_out_of_flow = Some(self.items.clone());
```
Comment (MDLC01) [inline crates/typst-library/src/layout/flow.rs:458]: I had to make `FlowItem` Clone, which is a bit sad. It should be noted, though, that this clone only happens when the last frame only contains out-of-flow elements, which is not often.

File: crates/typst-library/src/layout/flow.rs [hunk 2]
```diff
@@ -436,6 +440,24 @@ impl<'a> FlowLayouter<'a> {
 
     /// Finish the frame for one region.
     fn finish_region(&mut self, vt: &mut Vt) -> SourceResult<()> {
+        if let Some(items) = self.last_frame_only_out_of_flow.take() {
+            self.items.splice(0..0, items);
+            self.finished.pop();
```
Comment (MDLC01) [inline crates/typst-library/src/layout/flow.rs:445]: I feel like I should push an empty frame here to replace the one I just removed, but doing so makes the last test I added fail (it adds an empty page between the text and the block). How does it know what region frames correspond to if I just remove frames randomly?

**Comment by laurmaedje** [comment]
Just removing the last frame seems like a strange thing to do. It probably happens to work because the next frame is too large to fit into the first region and the parent flow handles it, but generally a multi-region layouter should produce one frame per region. 

One thing that might work is to `mem::take` the only-out-of-flow items at the start of finish_region to effectively create a completely empty frame and then, once that's done readd them to the current items. This way, you also wouldn't need a new field in the layouter.

File: crates/typst-library/src/layout/flow.rs (hunk 1 above)
Comment (MDLC01) [reply crates/typst-library/src/layout/flow.rs:458]: > Or wait, is that why you're pop()-ing a frame above?

Yes, in case the last frame was out-of-flow, we pop it from the list of finished frames before adding its content (which we cloned here) to the next frame.

File: crates/typst-library/src/layout/flow.rs [hunk 3]
```diff
@@ -436,6 +440,24 @@ impl<'a> FlowLayouter<'a> {
...
+            self.regions.next();
+            self.initial = self.regions.size;
+            self.has_footnotes = false;
+        }
+
+        if !self.items.is_empty()
+            && self.items.iter().all(|item| match item {
+                FlowItem::Placed { float: false, .. } => true,
+                FlowItem::Frame { frame, .. } => frame.size().is_zero(),
```
[the remark this answers is not in the document]
Comment (MDLC01) [reply crates/typst-library/src/layout/flow.rs:454]: Not sure what you mean here. The condition is `!self.items.is_empty() && …`. So an empty frame is never considered out-of-flow.

**Comment by MDLC01** [comment]
Oh god, what did I just do with the commit history!?

File: crates/typst-library/src/layout/flow.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (laurmaedje) [reply crates/typst-library/src/layout/flow.rs:454]: Sorry, I meant "I don't think a frame of size zero is necessarily out of flow". It might be size zero because it contains just metadata, but it might as well contain a box of height 0.

**Comment by laurmaedje** [comment]
> I'm not sure how to do that, because at at the start of finish_region, we no longer know whether the previous frame contained only out-of-flow elements (we would still need a boolean field, which I agree is better than cloning the elements).

What I meant is that rather than writing and then removing the frame with only out-of-flow elements, just don't create the frame at all, effectively deferring writing of the only out-of-flow elements. (Perhaps with the exception of the final finish_region call where we need to ensure that they are written.)

**Comment by MDLC01** [comment]
Turns out setting the frame size to `self.initial` instead of `Size::zero()` solved the issue of the last test not passing. Now all tests pass.

I will try to resolve the conflicts and solve the issue that frames with size zero are not necessarily out-of-flow, and then this will be ready to merge. In the meantime, I'm switching this PR to a draft.

**Comment by MDLC01** [comment]
I think this should now be safe to merge!

**Comment by laurmaedje** [comment]
Thank you, also for the patience!
