### PR TITLE
Fix bottom accent positioning in math

### LINKED ISSUE #5848: Bottom accent positioning in math is incorrect
### Description

An example:

```typ
$ accent(x y, \u{332}) accent(x + y, \u{332}) $
```

Image

Whilst there isn't any positioning information for bottom accents in the OpenType MATH spec, LuaTeX/XeTeX try to infer a decent position for them (I believe).

Related issue: https://github.com/typst/codex/issues/48.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by mkorje**
Closes #5848.

<details>

<summary>A ridiculously large test image showing all the accents with a bunch of different bases</summary>

```typ
--- playground ---
#set page(width: auto)

#let bottom-accents = (
  "\u{0323}", "\u{032C}", "\u{032D}", "\u{032E}", "\u{032F}", "\u{0330}",
  "\u{0331}", "\u{0332}", "\u{0333}", "\u{033A}", "\u{20E8}", "\u{20EC}",
  "\u{20ED}", "\u{20EE}", "\u{20EF}",
)

#let top-accents = (
  "\u{0307}", "\u{02C7}", "\u{02C6}", "\u{0306}", "\u{0311}", "\u{0303}",
  "\u{0304}", "\u{0305}", "\u{033F}", "\u{0346}", "\u{20DB}", "\u{20D1}",
  "\u{20D0}", "\u{20D6}", "\u{20D7}"
)

#let test(base, top, bot) = $accent(base, top) accent(base, bot) accent(accent(base, top), bot) accent(accent(base, bot), top)$

#for (top, bot) in top-accents.zip(bottom-accents) {
  $ test(x, top, bot) quad
    test(y, top, bot) quad
    test(p, top, bot) quad
    test(f, top, bot) quad
    test(b, top, bot) quad
    test(i, top, bot) quad
    test(j, top, bot) quad
    test(l, top, bot) quad
    test(x + y, top, bot) quad
    test(x y, top, bot) quad
    test(A, top, bot) quad
    test(H, top, bot) quad
    test(L, top, bot) quad
    test(I, top, bot) quad
    test(F, top, bot) quad
    test(J, top, bot) quad
    test(Q, top, bot) quad
    test(V, top, bot) quad
    test(sum, top, bot) quad
    test(integral, top, bot) quad
    test(xi, top, bot) quad
    test(Psi, top, bot) quad
    test(eta, top, bot) quad
    test(phi, top, bot) quad
    test(theta.alt, top, bot) $
}
```

playground

</details>

Figuring out shorthands for bottom accents (so that they are actually easy to use) is to be done in https://github.com/typst/codex/issues/48.

There's one thing that needs sorting - figuring out when a character is a bottom accent. Currently, I just store a list of the ones included in the [Unicode math class document](https://www.unicode.org/Public/math/revision-15/MathClassEx-15.html) in `impl Accent`. The best thing would probably be to check against the combining class code 220 (Below Combining Class). I think this will involve having to update icu data in typst-assets or smth then, which I have no idea how to do (and so will need help with). Though maybe this is overkill, especially when only a few (probably) bottom accents are ever actually used.

### CODE REVIEW

**Comment by MDLC01** [comment]
Does this also fix the problem described in https://github.com/typst/typst/issues/5848#issuecomment-2653671452, or should I create a separate issue for that?

**Comment by mkorje** [comment]
I think so, this looks right now to me:
playground

**Comment by laurmaedje** [comment]
Thank you!

File: crates/typst-library/src/math/accent.rs [hunk 1]
```diff
@@ -80,6 +80,19 @@ impl Accent {
...
+    /// Unicode math class document.
+    const BOTTOM: &[char] = &[
+        '\u{0323}', '\u{032C}', '\u{032D}', '\u{032E}', '\u{032F}', '\u{0330}',
+        '\u{0331}', '\u{0332}', '\u{0333}', '\u{033A}', '\u{20E8}', '\u{20EC}',
+        '\u{20ED}', '\u{20EE}', '\u{20EF}',
+    ];
+
+    /// Whether this accent is a bottom accent or not.
+    pub fn is_bottom(&self) -> bool {
+        Self::BOTTOM.contains(&self.0)
```
Comment (laurmaedje) [inline crates/typst-library/src/math/accent.rs:94]: I wasn't sure how well this would optimize, so I checked and it generates almost the same assembly as `matches!` :)

**Comment by mkorje** [comment]
> The best thing would probably be to check against the combining class code 220 (Below Combining Class). I think this will involve having to update icu data in typst-assets or smth then, which I have no idea how to do (and so will need help with).

@laurmaedje Do you think it'd be worth looking into this?

**Comment by laurmaedje** [comment]
Does the ICU database have more bottom accents than the ones you listed?

**Comment by mkorje** [comment]
There seem to be about 177 characters (not sure which version of Unicode this website is using) with below combining class: https://unicodeplus.com/combining/220; 2 with below left: https://unicodeplus.com/combining/218; and 4 with below right: https://unicodeplus.com/combining/222. Probably most won't be actually used in math by users, but still.

But it might be good to use the ICU data anyways as I'll need to know what is an accent regardless to finish https://github.com/typst/typst/issues/422 (I did most of the implementation a while ago now).

**Comment by laurmaedje** [comment]
The commands necessary to regenerate the files are [listed in the typst-assets source code](https://github.com/typst/typst-assets/blob/ab1295ff896444e51902e03c2669955e1d73604a/src/lib.rs#L11-L43). They need a little adjustment depending on how the projects are laid out on your disk. As-is, they work for mine because my `target` dir is unusually placed.

Before running this, you need to compile once while trying to access the new data and then`icu4x-datagen` will pick up what you tried to read from the compiled binary and include it in the asset.

**Comment by mkorje** [comment]
Alright, I'll have a go at adding them. On a slightly related note, there is https://github.com/typst/typst-assets/pull/8 which is hopefully straightforward! (I can then also open a PR on the Typst side if you'd like.)

**Comment by laurmaedje** [comment]
> On a slightly related note, there is https://github.com/typst/typst-assets/pull/8 which is hopefully straightforward!

Thanks, that wasn't on my radar anymore. Merged!

> I can then also open a PR on the Typst side if you'd like.

Sure!

**Comment by ParaN3xus** [comment]
I got this on main
image
```sh
$ cat test.typ
$ accent(x y, \u{332}) accent(x + y, \u{332}) $

$ cargo run c test.typ
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/typst c test.typ`
```

Maybe caused by #6377
