### PR TITLE
Clamp PDF page size to 3x3 units

### LINKED ISSUE #7292: Crash in PDF export when trying to `place` on a `margin: 0pt` and `width: auto` page
### Description

Reproducer (typst version 0.14.0):

```typ

#set page(width: auto, margin: 0pt)

#place(center+horizon, [1])
```

Then I click `Quick Export PDF` button in the webapp, it gives me the following:

Image

If running locally on my windows, typst@0.14.0 complains (this happens only if the format is PDF; SVG, PNG are OK)
```
thread 'main' panicked at ...\rustup\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\krilla-0.5.0\src\page.rs:48:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7ff7a0616522 - <unknown>
   1:     0x7ff7a063c4fb - <unknown>
   2:     0x7ff7a0611217 - <unknown>
   3:     0x7ff7a0616365 - <unknown>
   4:     0x7ff7a061ae6e - <unknown>
   5:     0x7ff7a061abe4 - <unknown>
   6:     0x7ff7a061ba0b - <unknown>
   7:     0x7ff7a061b782 - <unknown>
   8:     0x7ff7a06172df - <unknown>
   9:     0x7ff7a061b3ce - <unknown>
  10:     0x7ff7a0647f11 - <unknown>
  11:     0x7ff7a0647fcd - <unknown>
  12:     0x7ff7a0647e8e - <unknown>
  13:     0x7ff79d45eef7 - <unknown>
  14:     0x7ff79d18914e - <unknown>
  15:     0x7ff79d1925ed - <unknown>
  16:     0x7ff79d195fb7 - <unknown>
  17:     0x7ff79cfc691b - <unknown>
  18:     0x7ff79cfc6527 - <unknown>
  19:     0x7ff79cfc604d - <unknown>
  20:     0x7ff79cf1f9c7 - <unknown>
  21:     0x7ff79cfc5d2a - <unknown>
  22:     0x7ff79cfca12f - <unknown>
  23:     0x7ff79cfc3cf0 - <unknown>
  24:     0x7ff79cf4b1be - <unknown>
  25:     0x7ff79cfc3a28 - <unknown>
  26:     0x7ff79cf4c3c9 - <unknown>
  27:     0x7ff79cf4c172 - <unknown>
  28:     0x7ff79cf5a94b - <unknown>
  29:     0x7ff79cf6d29e - <unknown>
  30:     0x7ff79cf978d1 - <unknown>
  31:     0x7ff7a0608c55 - <unknown>
  32:     0x7ff79cf978ba - <unknown>
  33:     0x7ff79cf53939 - <unknown>
  34:     0x7ff7a06456ac - <unknown>
  35:     0x7ff9f9e7e8d7 - BaseThreadInitThunk
  36:     0x7ff9fbccc53c - RtlUserThreadStart
```

### Reproduction URL

https://typst.app/project/rKAQ4xs2pv3qIkEMusHOG6

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by saecki**
Fix #7292 by clamping the page size to 3x3 units. This is the minimum required until PDF 1.7, PDF 2.0 lifts the requirement.
This is similar to how `typst-render` clamps the image size to 1x1 pixels.

### CODE REVIEW

File: crates/typst-pdf/src/convert.rs [hunk 1]
```diff
@@ -81,52 +81,55 @@ fn convert_pages(gc: &mut GlobalContext, document: &mut Document) -> SourceResul
...
-                    &typst_page.frame,
-                    typst_page.fill_or_transparent(),
-                    surface,
-                    gc,
-                )
-            })?;
+        }
 
-            surface.finish();
+        // PDF 1.4 upwards to 1.7 specifies a minimum page size of 3x3 units.
```
Comment (laurmaedje) [inline crates/typst-pdf/src/convert.rs]: could you undo the unrelated code style change? For fix PRs, it's best to keep them minimal to make it easy to spot the diff and easy to backport.

Comment (laurmaedje) [reply crates/typst-pdf/src/convert.rs]: okay, I see that it's two commits now. though for fixes, I'd still prefer to have a simple squashable PR and reserve PRs that are merged fast-forward for somewhat larger things. sadly, GitHub doesn't really support stacked PR, but you can set another PR as the base branch, so that at least the diff is correct (it will still need to be rebased afterwards though).

regarding the order, it would in this case also be nicer to have the fix first and then the style change because otherwise the fix will immediately conflict when backporting.

Comment (saecki) [reply crates/typst-pdf/src/convert.rs]: Ok, done

File: tests/suite/layout/page.typ [hunk 2]
```diff
@@ -394,3 +394,12 @@ text
...
 2
+
+--- issue-7292-page-width-auto-margin-zero paged ---
+#set page(width: auto, height: 100pt, margin: 0pt)
+
+--- issue-7292-page-height-auto-margin-zero paged ---
+#set page(height: auto, margin: 0pt)
+
+--- issue-7292-page-size-auto-margin-zero paged ---
+#set page(width: auto, height: auto, margin: 0pt)
```
Comment (laurmaedje) [inline tests/suite/layout/page.typ:405]: these two are the same right? since the test runner already defaults to `height: auto`.

Comment (saecki) [reply tests/suite/layout/page.typ:405]: No the second one also sets `width: auto`, see the test images. I just wanted to be explicit above, I guess I could also set an explicit width on the `issue-7292-page-height-auto-margin-zero` test.

Comment (laurmaedje) [reply tests/suite/layout/page.typ:405]: Don't know what I was thinking. The images are clearly different after all...
