### PR TITLE
Fix math size resolving

### LINKED ISSUE #3729: Incorrect length measure in math superscript
### Description

The following code:
```typst
#let length = context repr(measure("--").width)
$ a length a ^ length $
```
renders as:
image

while the length provided in superscript should arguably be smaller. This is also happens with e.g. nested fractions, where content is also shrunk visually, but the measured length remains unchanged. Am I correct to believe the lengths should differ?

This can cause packages which rely on precise measurement to display things incorrectly in these contexts, like xarrow (which has not been too problematic so far because arrows are rarely used in superscript, nested fractions, etc.)

### Reproduction URL

_No response_

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by mkorje**
Fixes #3729.

The essence of this solution are the changes made in [crates/typst-library/src/text/mod.rs](https://github.com/typst/typst/compare/main...mkorje:typst:fix-math-sizing-resolving?expand=1#diff-0adb942019d59d0f74ea4230b8e4f398efeba0b944786b42f30edfeeaa141943) in this PR: When resolving `TextSize`, we take into account the current `MathSize` on the style chain. Everything else I've done follows on from that.

Relying less on MathContext in a number of places (as we needed it for the font for `scaled_font_size` mainly) makes some decent progress already towards solving #1193 and #3379, I think.

I've drafted this as I still need to add some more tests. I'll also probably still find some more places where things can be updated.

## Implementation stuff

The default value for the scriptPercentScaleDown and scriptScriptPercentScaleDown constants I've considered from 3 places:
- [MathML Core](https://www.w3.org/TR/mathml-core/#layout-constants-mathconstants), where they have the oddly specific values of 0.71 and 0.5041.
- [OpenType Spec](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathconstants-table), where the suggested values are 0.8 and 0.6.
- [Building OpenType math fonts](https://github.com/notofonts/math/blob/main/documentation/building-math-fonts/index.md#scriptpercentscaledown-scriptscriptpercentscaledown), which says the spec recommendations are bad, and that LaTeX's default setup basically uses 0.7 and 0.5.

As `f64` doesn't have Hash implemented, I'm using i16 (as it is stored in the font itself) and I've settled for now on 0.7 and 0.5

### CODE REVIEW

**Comment by mkorje** [comment]
The only issue I've come across so far with these changes is this totally not confusing behaviour:

```typ
#set page(width: auto, height: auto)
#let size = context [#text.size.to-absolute() #(1em).to-absolute()]
$ a^size $
```

playground

It appears Resolve is never called on the value retrieved from some element within context. I expected it to be resolved, matching what happens on the Rust side of things. But I guess that behaviour is understandable as you want to retrieve what you actually set a value to, not what it resolves to.

**Comment by laurmaedje** [comment]
The main reason `Resolve` is not called atm is that it's inconsistently used across the codebase and sometimes things are resolved manually. I didn't want to ship something inconsistent.

**Comment by mkorje** [comment]
I see. This PR makes Resolve be used consistently across the math part of the codebase, which is a step in the right direction I guess...

If it were consistent, is the intention then that when accessing fields they would always be resolved? For example would `#context math.mat.column-gap` return `5pt` instead of `0% + 0.5em`? It also seems it already kinda sometimes gets resolved:
```typ
#let size = context text.size
#size #text(1.5em)[#size]
```
Displays `10pt 15pt`.

(Note: Using the defaults from the test suite)

**Comment by laurmaedje** [comment]
> If it were consistent, is the intention then that when accessing fields they would always be resolved?

Probably yes, but I'm not fully decided yet.

File: crates/typst-layout/src/math/mod.rs [hunk 1]
```diff
@@ -58,12 +57,20 @@ pub fn layout_equation_inline(
 
     let mut locator = locator.split();
     let mut ctx = MathContext::new(engine, &mut locator, styles, region, &font);
+
+    let local = [
+        EquationElem::set_script_scale(ctx.constants.script_percent_scale_down()),
+        EquationElem::set_sscript_scale(ctx.constants.script_script_percent_scale_down()),
```
Comment (laurmaedje) [inline crates/typst-layout/src/math/mod.rs:63]: this could even be a single pair entry for a bit less runtime cost

File: crates/typst-layout/src/math/mod.rs [hunk 2]
```diff
@@ -110,9 +116,17 @@ pub fn layout_equation_block(
 
     let mut locator = locator.split();
     let mut ctx = MathContext::new(engine, &mut locator, styles, regions.base(), &font);
+
+    let local = [
+        EquationElem::set_script_scale(ctx.constants.script_percent_scale_down()),
+        EquationElem::set_sscript_scale(ctx.constants.script_script_percent_scale_down()),
+    ]
+    .map(|p| p.wrap());
```
Comment (laurmaedje) [inline crates/typst-layout/src/math/mod.rs:124]: could we deduplicate that with the one in layout_equation_inline?

File: crates/typst-library/src/math/attach.rs [hunk 3]
```diff
@@ -152,5 +152,7 @@ pub struct StretchElem {
 
     /// The size to stretch to, relative to the maximum size of the glyph and
     /// its attachments.
-    pub size: Smart<Rel<Length>>,
+    #[resolve]
+    #[default(Rel::one())]
+    pub size: Rel<Length>,
```
Comment (laurmaedje) [inline crates/typst-library/src/math/attach.rs:157]: Technically a breaking change, but an okay one

**Review by laurmaedje — APPROVED** [review]
Reading the diff of this made me happy. :)

File: crates/typst-library/src/math/attach.rs (hunk 3 above)
Comment (mkorje) [reply crates/typst-library/src/math/attach.rs:157]: Yes, I did this in a couple places. It seems quite obvious now that the those don't need to be smart.

File: crates/typst-layout/src/math/mod.rs (hunk 2 above)
Comment (mkorje) [reply crates/typst-layout/src/math/mod.rs:124]: Will do

File: crates/typst-layout/src/math/mod.rs (hunk 1 above)
Comment (mkorje) [reply crates/typst-layout/src/math/mod.rs:63]: That seems reasonable. I will modify it.

**Comment by mkorje** [comment]
I was going to maybe try fix nested math content having its styles overwritten by the inner equation, as in the `math-size-math-content-1` and `math-size-math-content-2` tests. Though I probably won't get to that for a bit, so I'm happy to leave that for another PR so this can go through.

File: tests/ref/math-size-math-content-3.png
Comment (laurmaedje) [inline tests/ref/math-size-math-content-3.png:1]: this image is a bit confusing

Comment (laurmaedje) [reply tests/ref/math-size-math-content-3.png:1]: I assume the image is the current bad case and once it's fixed, it'll make sense? Still, it's kinda confusing now and maybe it should be adjusted.

Comment (mkorje) [reply tests/ref/math-size-math-content-3.png:1]: Yeah that's what I was getting at. Though even once its fixed, its still "wrong".

I wanted to add a case for a single expr in math as since it doesnt get wrapped in math, it won't be fixed when the other ones (tests -1 and -2) are fixed.

File: crates/typst-layout/src/math/run.rs [hunk 4]
```diff
@@ -181,28 +182,23 @@ impl MathRun {
...
         let rows: Vec<_> = self.rows();
         let row_count = rows.len();
         let alignments = alignments(&rows);
 
         let leading = if EquationElem::size_in(styles) >= MathSize::Text {
             ParElem::leading_in(styles)
         } else {
-            let font_size = scaled_font_size(ctx, styles);
-            TIGHT_LEADING.at(font_size)
+            TIGHT_LEADING.at(TextElem::size_in(styles))
```
[the remark this answers is not in the document]
Comment (mkorje) [reply crates/typst-layout/src/math/run.rs:201]: Knew I'd end up missing something

File: tests/ref/math-size-math-content-3.png
Comment (laurmaedje) [reply tests/ref/math-size-math-content-3.png:1]: hmmm. I still think the image should indicate whether the test passes or not.

Comment (mkorje) [reply tests/ref/math-size-math-content-3.png:1]: I could just make it then `sum != height(sum) instead, hopefully that's clearer.

**Comment by laurmaedje** [comment]
Thank you!
