### PR TITLE
Let type constructor/field access error report the name correctly

### LINKED ISSUE #3110: Weird error when attempting to call `content`
### Description

Running the Typst code below on 0.10.0:

```typ
content()
```

yields:

```
Error: type self does not have a constructor
   ╭─[/main.typ:8:2]
   │
 8 │ #content()
   │  ───────  
   │            
───╯
```

Which is a bit unexpected (it's not the `self` type but the `content` type).

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Leedehai**
Fix #3110 

I agree it's kinda confusing. Maybe the `self` was caused by a search-and-replace operation? If the name is deliberately omitted, maybe it should write `itself`.

The `short_name()` (which returns `self.0.name`) of the type is set by https://github.com/typst/typst/blob/7eebafa7837ec173a7b2064ae60fd45b5413d17c/crates/typst-macros/src/ty.rs#L62 and then by https://github.com/typst/typst/blob/46053b62e5d87118f33476d3c7f6ddf794fbafeb/crates/typst-macros/src/util.rs#L168

The location of the test is debatable (how about a new file in `tests/typ/compiler/`?), though.

### CODE REVIEW

File: crates/typst/src/foundations/ty.rs [hunk 1]
```diff
@@ -94,25 +94,27 @@ impl Type {
             .constructor
             .as_ref()
             .map(|lazy| Func::from(*lazy))
-            .ok_or_else(|| eco_format!("type self does not have a constructor"))
+            .ok_or_else(|| {
+                eco_format!("type `{}` does not have a constructor", self.short_name())
```
Comment (laurmaedje) [inline crates/typst/src/foundations/ty.rs:98]:
```suggestion
                eco_format!("type {self} does not have a constructor")
```

File: crates/typst/src/foundations/ty.rs [hunk 2]
```diff
@@ -94,25 +94,27 @@ impl Type {
...
         &(self.0).0.scope
     }
 
     /// Get a field from this type's scope, if possible.
     pub fn field(&self, field: &str) -> StrResult<&'static Value> {
-        self.scope()
-            .get(field)
-            .ok_or_else(|| eco_format!("type self does not contain field `{}`", field))
+        self.scope().get(field).ok_or_else(|| {
+            eco_format!("type `{}` does not contain field `{}`", self.short_name(), field)
```
Comment (laurmaedje) [inline crates/typst/src/foundations/ty.rs:110]:
```suggestion
            eco_format!("type {self} does not contain field `{field}`")
```

**Comment by laurmaedje** [comment]
Thanks!
