### PR TITLE
Implement math kerning and fix various `math.attach` bugs

### LINKED ISSUE #4759: Implement math kerning
### Description

There is a [MathKernInfo table](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathkerninfo-table) in the OpenType MATH spec, which provides values used to kern subscripts and superscripts relative to their base.

(There is, in fact, a [bug in the spec](https://github.com/MicrosoftDocs/typography-issues/issues/1147). And some fonts have bugs in the above table, leading to [wrong implementations providing better results sometimes](https://github.com/latex3/unicode-math/issues/592).)

The only problem is, there aren't that many OpenType MATH fonts, and even fewer ones that actually contain this information! Typst's default math font, New Computer Modern Math, does _not_ contain any of this information. I've collated what I believe to be every OpenType font that implements the MATH table, and have begun investigating their support for the features in the OpenType MATH spec.

## OpenType Math Fonts

The primary source for the below is [Which OpenType Math fonts are available?](https://tex.stackexchange.com/questions/425098/which-opentype-math-fonts-are-available). If you know of a font that I've missed, please let me know so I can add it!

<details>
<summary>Table of OpenType math fonts</summary>

| Font | License | Accompanying text font | Derived from |
| - | - | - | - |
| [Asana Math](https://www.ctan.org/pkg/asana-math) | [OFL](https://openfontlicense.org/) | [TeX Gyre Pagella](https://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella) | [Palatino](https://en.wikipedia.org/wiki/Palatino) |
| [Garamond Math](https://github.com/YuanshengZhao/Garamond-Math) | [OFL](https://openfontlicense.org/) | [EB Garamond](https://github.com/georgd/EB-Garamond), [EB Garamond 12](https://github.com/octaviopardo/EBGaramond12) | [Garamond](https://en.wikipedia.org/wiki/Garamond) |
| [Erewhon Math](https://ctan.org/pkg/erewhon-math) | [OFL](https://openfontlicense.org/) | [Erewhon](https://ctan.org/pkg/erewhon) | [Utopia](https://en.wikipedia.org/wiki/Utopia_%28typeface%29) |
| [KpMath](https://ctan.org/pkg/kpfonts-otf) | [OFL](https://openfontlicense.org/) | [Kp-Fonts](https://ctan.org/pkg/kpfonts-otf) | [Palatino](https://en.wikipedia.org/wiki/Palatino) |
| [Latin Modern Math](https://www.gust.org.pl/projects/e-foundry/lm-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [Latin Modern](https://www.gust.org.pl/projects/e-foundry/latin-modern) | [Computer Modern](https://en.wikipedia.org/wiki/Computer_Modern) |
| [New Computer Modern Math](https://ctan.org/pkg/newcomputermodern) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [New Computer Modern](https://ctan.org/pkg/newcomputermodern) | [Computer Modern](https://en.wikipedia.org/wiki/Computer_Modern) |
| [TeX Gyre Bonum Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [TeX Gyre Bonum](https://www.gust.org.pl/projects/e-foundry/tex-gyre/bonum) | [ITC Bookman](https://en.wikipedia.org/wiki/Bookman_(typeface)#ITC_Bookman) |
| [TeX Gyre Pagella Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [TeX Gyre Pagella](https://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella) | [Palatino](https://en.wikipedia.org/wiki/Palatino) |
| [TeX Gyre Schola Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [TeX Gyre Schola](https://www.gust.org.pl/projects/e-foundry/tex-gyre/schola) | [Century Schoolbook](https://en.wikipedia.org/wiki/Century_type_family#Century_Schoolbook) |
| [TeX Gyre Termes Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [TeX Gyre Termes](https://www.gust.org.pl/projects/e-foundry/tex-gyre/termes) | [Times New Roman](https://en.wikipedia.org/wiki/Times_New_Roman) |
| [TeX Gyre DejaVu Math](https://www.gust.org.pl/projects/e-foundry/tex-gyre-dejavu-math) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [DejaVu](https://github.com/dejavu-fonts/dejavu-fonts) | [Bitstream Vera](https://en.wikipedia.org/wiki/Bitstream_Vera) |
| [STIX Math](https://github.com/stipub/stixfonts) | [OFL](https://openfontlicense.org/) | [STIX](https://github.com/stipub/stixfonts) | [Times New Roman](https://en.wikipedia.org/wiki/Times_New_Roman) |
| [XTIS Math](https://github.com/aliftype/xits) | [OFL](https://openfontlicense.org/) | [XITS](https://github.com/aliftype/xits) | [Times New Roman](https://en.wikipedia.org/wiki/Times_New_Roman) |
| [STIX Two Math](https://github.com/stipub/stixfonts) | [OFL](https://openfontlicense.org/) | [STIX Two](https://github.com/stipub/stixfonts) | [Times New Roman](https://en.wikipedia.org/wiki/Times_New_Roman) |
| [Libertinus Math](https://github.com/alerque/libertinus) | [OFL](https://openfontlicense.org/) | [Libertinus](https://github.com/alerque/libertinus) | [Times New Roman](https://en.wikipedia.org/wiki/Times_New_Roman) |
| [Fira Math](https://github.com/firamath/firamath) | [OFL](https://openfontlicense.org/) | [FiraGo](https://github.com/bBoxType/FiraGO) | [Fira Sans](https://en.wikipedia.org/wiki/Fira_(typeface)) |
| [Noto Sans Math](https://github.com/notofonts/math) | [OFL](https://openfontlicense.org/) | [Noto](https://fonts.google.com/noto) | [Noto](https://en.wikipedia.org/wiki/Noto_fonts) |
| [Lete Sans Math](https://github.com/abccsss/LeteSansMath) | [OFL](https://openfontlicense.org/) | [Lato](https://www.latofonts.com/) | [Lato](https://en.wikipedia.org/wiki/Lato_(typeface)) |
| [GFS Neohellenic Math](https://greekfontsociety-gfs.gr/typefaces/Math) | [OFL](https://openfontlicense.org/) | [GFS Neohellenic](https://greekfontsociety-gfs.gr/typefaces/20th_21st_century) | [New Hellenic](https://en.wikipedia.org/wiki/Porson_(typeface)#Legacy) |
| [Old Standard Math](https://git.robertalessi.net/oldstandard/about/) | [GFL](https://www.gust.org.pl/projects/e-foundry/licenses) | [Old Standard](https://git.robertalessi.net/oldstandard/about/) | [Century Schoolbook](https://en.wikipedia.org/wiki/Century_type_family#Related_digital_revivals) |
| [XCharter Math](https://ctan.org/pkg/xcharter-math) | [OFL](https://openfontlicense.org/) | [XCharter](https://ctan.org/pkg/xcharter) | [Bitstream Charter](https://en.wikipedia.org/wiki/Bitstream_Charter) |
| [Concrete Math](https://ctan.org/pkg/concmath-otf) | [OFL](https://openfontlicense.org/) | [CMU Concrete](https://cm-unicode.sourceforge.io/index.html) | [Concrete Roman](https://en.wikipedia.org/wiki/Concrete_Roman) |
| [Nagwa TK](https://fonts.nagwa.com/tk/) | [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en) | [Nagwa TK](https://fonts.nagwa.com/tk/) | [Tekton](https://fonts.adobe.com/fonts/tekton) |
| [Euler Math](https://ctan.org/pkg/euler-math) | [OFL](https://openfontlicense.org/) | [CMU Concrete](https://cm-unicode.sourceforge.io/index.html), [TeX Gyre Pagella](https://www.gust.org.pl/projects/e-foundry/tex-gyre/pagella) | [AMS Euler](https://en.wikipedia.org/wiki/AMS_Euler) |
| [Lucida Math](https://tug.org/store/lucida/opentype.html) | Commercial | [Lucida](https://tug.org/store/lucida/opentype.html) | [Lucida](https://en.wikipedia.org/wiki/Lucida) |
| [Minion Math](http://typoma.de/en/fonts.html) | Commercial | [Minion Pro](https://fonts.adobe.com/fonts/minion), [Minion 3](https://fonts.adobe.com/fonts/minion-3) | [Minion](https://en.wikipedia.org/wiki/Minion_(typeface)) |
| [Cambria Math](https://learn.microsoft.com/en-us/typography/font-list/cambria-math) | Proprietary | [Cambria](https://learn.microsoft.com/en-us/typography/font-list/cambria) | [Cambria](https://en.wikipedia.org/wiki/Cambria_(typeface)) |
</details>

## Support for the OpenType MATH spec

The main source for the below table has been myself using FontForge and other tools to inspect font data. It is still a WIP, and I'll update it as I progress. Note that the "categories" I've split them up into is fairly broad and not comprehensive.

Cambria Math (Microsoft's font) is the best font in regards to the standard (as Microsoft made the standard :|). 

<details>
<summary>Table of fonts' OpenType MATH support</summary>

| Font | Constants | Exten Shapes | Italic Correction | Top Accent | Math Kern |
| - | - | - | - | - | - |
| [Asana Math](https://www.ctan.org/pkg/asana-math) | | | | | |
| [Garamond Math](https://github.com/YuanshengZhao/Garamond-Math) | ✓ | ✓ | ✗[^1] | ✓ | ✓ |
| [Erewhon Math](https://ctan.org/pkg/erewhon-math) | | | | | |
| [KpMath](https://ctan.org/pkg/kpfonts-otf) | | | | | |
| [Latin Modern Math](https://www.gust.org.pl/projects/e-foundry/lm-math) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [New Computer Modern Math](https://ctan.org/pkg/newcomputermodern) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [TeX Gyre Bonum Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | | | | | |
| [TeX Gyre Pagella Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [TeX Gyre Schola Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | | | | | |
| [TeX Gyre Termes Math](https://www.gust.org.pl/projects/e-foundry/tg-math) | | | | | |
| [TeX Gyre DejaVu Math](https://www.gust.org.pl/projects/e-foundry/tex-gyre-dejavu-math) | | | | | |
| [STIX Math](https://github.com/stipub/stixfonts) | | | | | |
| [XTIS Math](https://github.com/aliftype/xits) | | | | | |
| [STIX Two Math](https://github.com/stipub/stixfonts) | ✓ | ✓ | ✓ | ✓ | ✓ |
| [Libertinus Math](https://github.com/alerque/libertinus) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [Fira Math](https://github.com/firamath/firamath) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [Noto Sans Math](https://github.com/notofonts/math) | ✓ | ✓ | ✓ | ✓ | ✗ |
| [Lete Sans Math](https://github.com/abccsss/LeteSansMath) | | | | | |
| [GFS Neohellenic Math](https://greekfontsociety-gfs.gr/typefaces/Math) | | | | | |
| [Old Standard Math](https://git.robertalessi.net/oldstandard/about/) | | | | | |
| [XCharter Math](https://ctan.org/pkg/xcharter-math) | | | | | |
| [Concrete Math](https://ctan.org/pkg/concmath-otf) | | | | | |
| [Nagwa TK](https://fonts.nagwa.com/tk/) | | | | | |
| [Euler Math](https://ctan.org/pkg/euler-math) | | | | | |
| [Lucida Math](https://tug.org/store/lucida/opentype.html) | | | | | |
| [Minion Math](http://typoma.de/en/fonts.html) | | | | | |
| [Cambria Math](https://learn.microsoft.com/en-us/typography/font-list/cambria-math) | ✓ | ✓ | ✓ | ✓ | ✓ |

[^1]: The font has italic correction values only for integrals and their variants.
</details>

There's also offset values in the [MathValueRecord](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathvaluerecord), which provide corrections to given values at particular display resolutions. These are present in Cambria Math.

### Use Case

Better mathematics typesetting!

### LINKED ISSUE #4760: Math attachments: top and bottom attachments have incorrect frame size
### Description

I believe I've found 3 bugs with how top and bottom attachments are laid out in Typst.

## 1

When laying out only top and/or bottom attachments, their displacement by the italics correction of the base is not reflected in the final AttachElem's frame size.

https://github.com/typst/typst/blob/d84a7e423b53e9b5740720270b132da60c8a3fea/crates/typst/src/math/attach.rs#L382-L384

An example:

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| issue2_1_incorrect | issue2_1_correct |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 1cm, height: 1.5cm)
#set align(center + horizon)

// From math-attach-integral test.
$limits(\u{2a1b})_a^b$
```
</details>

## 2

If top and/or bottom attachments are present as well one of the four corners, the top and bottom attachments' widths are not taken into account in the final `AttachElem`'s frame width.

https://github.com/typst/typst/blob/d84a7e423b53e9b5740720270b132da60c8a3fea/crates/typst/src/math/attach.rs#L303-L312

An example:

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| issue2_2_incorrect | issue2_2_correct |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 3cm, height: auto)

$
  a + attach(product, t: 123456789) + b \
  a + attach(product, t: 123456789, bl: x) + b \
$
```
</details>

## 3

The final `AttachElem` frame goes too low when there is a bottom attachment with a bl/br attachment.

https://github.com/typst/typst/blob/d84a7e423b53e9b5740720270b132da60c8a3fea/crates/typst/src/math/attach.rs#L276-L284

Using shift_up and shift_down to calculate the top and bottom attachment's contribution to the max ascent/descent is incorrect. It isn't an issue for the top attachment as the baseline of tl/tr is below the top of the base's bounding box. Whereas the baseline of bl/br is below the bottom of the base's bouding box.

An example:

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| issue2_3_incorrect | issue2_3_correct |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 3cm, height: auto)

$
  attach(limits(a), b: b, br: y),
  attach(
    Pi, t: alpha, b: beta,
    tr: 2+3, br: 6,
  )
$
```
</details>

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### LINKED ISSUE #4761: Math attachments: `spaceAfterScript` used incorrectly
### Description

Typst is incorrectly adding `spaceAfterScript` (from the [MathConstants table](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathconstants-table)) to the end of any `AttachElem` with `tl`, `tr`, `bl`, `br` attachments, instead of only when there are right attachments present.

https://github.com/typst/typst/blob/d84a7e423b53e9b5740720270b132da60c8a3fea/crates/typst/src/math/attach.rs#L306-L312

Further, this spacing is not applied to prescripts. This was [recently clarified in the spec](https://github.com/MicrosoftDocs/typography-issues/issues/1135), and now the description for `spaceAfterScript` reads as follows.

> Extra white space to be added after each subscript and superscript that occurs after a baseline element, and before each subscript and superscript that occurs before a baseline element. ...

An example:

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| issue1_incorrect | issue1_correct |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 4.5cm, height: auto)

// From math-attach-prescripts test.
$
attach(upright(O), bl: 8, tl: 16, br: 2, tr: 2-),
attach("Pb", bl: 82, tl: 207) + attach(upright(e), bl: -1, tl: 0) + macron(v)_e \
$
```
</details>

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by mkorje**
Closes #4759, closes #4760, closes #4761.

<details>
<summary>Updated test explanations</summary>

`gradient-math-misc` - bottom of bounding box is too low #4760 (3).
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_gradient-math-misc | DEBUG_gradient-math-misc |

`math-attach-high` - #4761.
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-high | DEBUG_math-attach-high |

`math-attach-horizontal-align` - #4761.
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-horizontal-align | DEBUG_math-attach-horizontal-align |

`math-attach-integral` - #4760 (1).
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-integral | DEBUG_math-attach-integral |

`math-attach-mixed` - #4761 & #4760 (3).
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-mixed | DEBUG_math-attach-mixed |

`math-attach-nested` - #4761 & #4760 (3).
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-nested | DEBUG_math-attach-nested |

`math-attach-prescripts` - #4761.
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-attach-prescripts | DEBUG_math-attach-prescripts |

`math-spacing-decorated` - #4761.
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) (incorrect) | Corrected |
| - | - |
| DEBUG_math-spacing-decorated | DEBUG_math-spacing-decorated |
</details>

<details>
<summary>New tests added</summary>

```typ
--- math-attach-limit-long ---
// Test long limit attachments.
$ attach(product, t: 123456789) attach(product, t: 123456789, bl: x) \
  attach(product, b: 123456789) attach(product, b: 123456789, tr: x) $
$attach(limits(product), t: 123456789) attach(limits(product), t: 123456789, bl: x)$

$attach(limits(product), b: 123456789) attach(limits(product), b: 123456789, tr: x)$
```

math-attach-limit-long

```typ
--- math-attach-kerning ---
// Test math kerning.
#show math.equation: set text(font: "STIX Two Math")

$ L^A Y^c R^2 delta^y omega^f a^2 t^w gamma^V p^+ \
  b_lambda f_k p_i x_1 x_j x_A y_l y_y beta_s theta_k \
  J_0 Y_0 T_1 T_f V_a V_A F_j cal(F)_j lambda_y \
  attach(W, tl: l) attach(A, tl: 2) attach(cal(V), tl: beta)
  attach(cal(P), tl: iota) attach(f, bl: i) attach(A, bl: x)
  attach(cal(J), bl: xi) attach(cal(A), bl: m) $
```

math-attach-kerning

```typ
--- math-attach-kerning-mixed ---
// Test mixtures of math kerning.
#show math.equation: set text(font: "STIX Two Math")

$ x_1^i x_2^lambda x_2^(2alpha) x_2^(k+1) x_2^(-p_(-1)) x_j^gamma \
  f_2^2 v_0^2  z_0^2 beta_s^2 xi_i^k J_1^2 N_(k y)^(-1) V_pi^x \
  attach(J, tl: 1, br: i) attach(P, tl: i, br: 2) B_i_0 phi.alt_i_(n-1)
  attach(A, tr: x, bl: x, br: x, tl: x) attach(F, tl: i, tr: f) \
  attach(cal(A), tl: 2, bl: o) attach(cal(J), bl: l, br: A)
  attach(cal(y), tr: p, bl: n t) attach(cal(O), tl: 16, tr: +, br: sigma)
  attach(italic(Upsilon), tr: s, br: Psi, bl: d) $
```

math-attach-kerning-mixed

</details>

<details>
<summary>Math kerning examples (with STIX Two Math font)</summary>

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) | PR |
| - | - |
| math-kerning-stix-old | math-kerning-stix-new |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 4cm, height: auto)
#show math.equation: set text(font: "STIX Two Math")

$
  P_2 P^2 P_2^2 quad
  f_2 f^2 f_2^2 \
  A_2 A^2 A_2^2 quad
  F_2 F^2 F_2^2 \
  P_2 P^2 P_2^2 quad
  T_2 T^2 T_2^2 \
  V_2 V^2 V_2^2 quad
  W_2 W^2 W_2^2 \
  Y_2 Y^2 Y_2^2 quad
  upright(Y)_2 upright(Y)^2 upright(Y)_2^2 \
  Gamma_2 Gamma^2 Gamma_2^2 quad
  Delta_2 Delta^2 Delta_2^2 \
  Lambda_2 Lambda^2 Lambda_2^2 quad
  Rho_2 Rho^2 Rho_2^2 \
  Tau_2 Tau^2 Tau_2^2 quad
  Upsilon_2 Upsilon^2 Upsilon_2^2 \
  Psi_2 Psi^2 Psi_2^2 quad
  nabla_2 nabla^2 nabla_2^2 \
  italic(Gamma)_2 italic(Gamma)^2 italic(Gamma)_2^2 quad
  italic(Delta)_2 italic(Delta)^2 italic(Delta)_2^2 \
  italic(Lambda)_2 italic(Lambda)^2 italic(Lambda)_2^2 quad
  italic(Upsilon)_2 italic(Upsilon)^2 italic(Upsilon)_2^2 \
  italic(Psi)_2 italic(Psi)^2 italic(Psi)_2^2 quad
  ℘_2 ℘^2 ℘_2^2 \
  lambda_2 lambda^2 lambda_2^2 quad
  partial_2 partial^2 partial_2^2 \
$

$
  F_j quad
  y_A quad
  y_l quad y_y \
  V_a quad
  V_x^x quad
  attach(J, tl: 1, br: i) quad
  attach(A, tr: x, bl: x, br: x) \
  attach(cal(y), br: x, tl: i) quad
  xi_i^k quad
  attach(cal(A), tl: 2) quad
  attach(cal(A), tl: x) \
  attach(cal(J), br: A, bl: l) quad
  attach(cal(J), br: x, bl: 2) quad
  x_A quad
  x_x \
$

// Bugs in STIX Two Math font
$
  V_A quad cal(F)_j
$
```

</details>

</details>

<details>
<summary>Math kerning examples (with Cambria Math font)</summary>

(Typst is panicking when I try to create PNGs, so these are SVGs. See #4786.)
| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) | PR |
| - | - |
| math-kerning-cambria-old | math-kerning-cambria-new |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 4cm, height: auto)
#show math.equation: set text(font: "Cambria Math")

$
  P_2 P^2 P_2^2 quad
  f_2 f^2 f_2^2 \
  A_2 A^2 A_2^2 quad
  F_2 F^2 F_2^2 \
  P_2 P^2 P_2^2 quad
  T_2 T^2 T_2^2 \
  V_2 V^2 V_2^2 quad
  W_2 W^2 W_2^2 \
  Y_2 Y^2 Y_2^2 quad
  upright(Y)_2 upright(Y)^2 upright(Y)_2^2 \
  Gamma_2 Gamma^2 Gamma_2^2 quad
  Delta_2 Delta^2 Delta_2^2 \
  Lambda_2 Lambda^2 Lambda_2^2 quad
  Rho_2 Rho^2 Rho_2^2 \
  Tau_2 Tau^2 Tau_2^2 quad
  Upsilon_2 Upsilon^2 Upsilon_2^2 \
  Psi_2 Psi^2 Psi_2^2 quad
  nabla_2 nabla^2 nabla_2^2 \
  italic(Gamma)_2 italic(Gamma)^2 italic(Gamma)_2^2 quad
  italic(Delta)_2 italic(Delta)^2 italic(Delta)_2^2 \
  italic(Lambda)_2 italic(Lambda)^2 italic(Lambda)_2^2 quad
  italic(Upsilon)_2 italic(Upsilon)^2 italic(Upsilon)_2^2 \
  italic(Psi)_2 italic(Psi)^2 italic(Psi)_2^2 quad
  ℘_2 ℘^2 ℘_2^2 \
  lambda_2 lambda^2 lambda_2^2 quad
  partial_2 partial^2 partial_2^2 \
$

$
  F_j quad
  y_A quad
  y_l quad y_y \
  V_a quad
  V_x^x quad
  attach(J, tl: 1, br: i) quad
  attach(A, tr: x, bl: x, br: x) \
  attach(cal(y), br: x, tl: i) quad
  xi_i^k quad
  attach(cal(A), tl: 2) quad
  attach(cal(A), tl: x) \
  attach(cal(J), br: A, bl: l) quad
  attach(cal(J), br: x, bl: 2) quad
  x_A quad
  x_x \
$

// Bugs in STIX Two Math font
$
  V_A quad cal(F)_j
$
```

</details>

</details>

<details>
<summary>Math kerning examples (with New Computer Modern Math font) - NO CHANGE</summary>

| [main](https://github.com/typst/typst/commit/d84a7e423b53e9b5740720270b132da60c8a3fea) | PR |
| - | - |
| math-kerning-ncm-old | math-kerning-ncm-new |

<details>
<summary>Typst code</summary>

```typst
#set page(width: 4cm, height: auto)

$
  P_2 P^2 P_2^2 quad
  f_2 f^2 f_2^2 \
  A_2 A^2 A_2^2 quad
  F_2 F^2 F_2^2 \
  P_2 P^2 P_2^2 quad
  T_2 T^2 T_2^2 \
  V_2 V^2 V_2^2 quad
  W_2 W^2 W_2^2 \
  Y_2 Y^2 Y_2^2 quad
  upright(Y)_2 upright(Y)^2 upright(Y)_2^2 \
  Gamma_2 Gamma^2 Gamma_2^2 quad
  Delta_2 Delta^2 Delta_2^2 \
  Lambda_2 Lambda^2 Lambda_2^2 quad
  Rho_2 Rho^2 Rho_2^2 \
  Tau_2 Tau^2 Tau_2^2 quad
  Upsilon_2 Upsilon^2 Upsilon_2^2 \
  Psi_2 Psi^2 Psi_2^2 quad
  nabla_2 nabla^2 nabla_2^2 \
  italic(Gamma)_2 italic(Gamma)^2 italic(Gamma)_2^2 quad
  italic(Delta)_2 italic(Delta)^2 italic(Delta)_2^2 \
  italic(Lambda)_2 italic(Lambda)^2 italic(Lambda)_2^2 quad
  italic(Upsilon)_2 italic(Upsilon)^2 italic(Upsilon)_2^2 \
  italic(Psi)_2 italic(Psi)^2 italic(Psi)_2^2 quad
  ℘_2 ℘^2 ℘_2^2 \
  lambda_2 lambda^2 lambda_2^2 quad
  partial_2 partial^2 partial_2^2 \
$

$
  F_j quad
  y_A quad
  y_l quad y_y \
  V_a quad
  V_x^x quad
  attach(J, tl: 1, br: i) quad
  attach(A, tr: x, bl: x, br: x) \
  attach(cal(y), br: x, tl: i) quad
  xi_i^k quad
  attach(cal(A), tl: 2) quad
  attach(cal(A), tl: x) \
  attach(cal(J), br: A, bl: l) quad
  attach(cal(J), br: x, bl: 2) quad
  x_A quad
  x_x \
$

// Bugs in STIX Two Math font
$
  V_A quad cal(F)_j
$
```

</details>

</details>

### CODE REVIEW

**Comment by laurmaedje** [comment]
I merged the typst-dev-assets PR, so you can bump here.

File: crates/typst/src/math/attach.rs [hunk 1]
```diff
@@ -465,7 +566,84 @@ fn compute_shifts_up_and_down(
...
+                script.kern_at_height(ctx, opposite_corner(pos), corr_height_top);
+
+            // Take the smaller kerning amount (and so the larger value).
+            sum.max(base_kern + subscript_kern)
+        }
+    }
+}
+
+/// Get the opposite corner.
+fn opposite_corner(position: Corner) -> Corner {
```
Comment (laurmaedje) [inline crates/typst/src/math/attach.rs:637]: I think is generally useful and could be `Corner::inv`, similar to `Dir::inv` and `Align::inv`.

File: crates/typst/src/math/attach.rs [hunk 2]
```diff
@@ -465,7 +566,84 @@ fn compute_shifts_up_and_down(
...
+            let sum = base_kern + subscript_kern;
+
+            let base_kern = base.kern_at_height(ctx, pos, corr_height_top);
+            let subscript_kern =
+                script.kern_at_height(ctx, opposite_corner(pos), corr_height_top);
+
+            // Take the smaller kerning amount (and so the larger value).
+            sum.max(base_kern + subscript_kern)
+        }
+    }
```
Comment (laurmaedje) [inline crates/typst/src/math/attach.rs:633]:
```suggestion
    // This process is described under the MathKernInfo table in the OpenType
    let (corr_height_top, corr_height_bot) = match pos {
        // Calculate two correction heights for superscripts:
        // - The distance from the base's baseline to the bottom of the
        //   superscript's bounding box.
        // - The distance from the superscript's baseline to the top of the
        //   base's bounding box.
        Corner::TopLeft | Corner::TopRight => {
            (base.ascent() - shift, shift - script.descent())
        }
        // Calculate two correction heights for subscripts:
        // - The distance from the subscript's baseline to the bottom of the
        //   base's bounding box.
        // - The distance from the base's baseline to the top of the
        //   subscript's bounding box.
        Corner::BottomLeft | Corner::BottomRight => {
            (script.ascent() - shift, shift - base.descent())
        }
    };

    // Calculate the sum of kerning values for each correction height.
    let summed_kern = |height| {
        let base_kern = base.kern_at_height(ctx, pos, height);
        let attach_kern = script.kern_at_height(ctx, opposite_corner(pos), height);
        base_kern + attach_kern
    };

    // Take the smaller kerning amount (and so the larger value). This process
    // is described under the MathKernInfo table in the OpenType MATH spec. Note
    // that there is a bug in the spec (as of 2024-08-15): it says to take the
    // minimum of the two sums, but as the kerning value is usually negative it
    // really means the smaller kern. The current wording of the spec could
    // result in glyphs colliding.
    summed_kern(corr_height_top).max(summed_kern(corr_height_bot))
```

File: crates/typst/src/math/attach.rs [hunk 3]
```diff
@@ -261,145 +261,246 @@ fn layout_attachments(
...
-        width.set_max(t.width());
-        height += t.height() + top_gap;
-        base_offset = top_gap + t.height();
-    }
+    base: &MathFragment,
+    [tr, br]: [&Option<MathFragment>; 2],
+    (tr_shift, br_shift): (Abs, Abs),
+    space_after_post_script: Abs,
+) -> ((Abs, Abs), (Abs, Abs)) {
+    let tr_values = if let Some(tr) = tr {
```
Comment (laurmaedje) [inline crates/typst/src/math/attach.rs:384]: Potentially (not sure about this suggestion), the fairly frequent `if let Some(x) = x { /* Do stuff */ } else { /* Something amount of Abs::zero()s /* }` could be deduplicated with a helper function (that effectively does what `Option::map_or_default` would do if it existed).

**Review by laurmaedje — COMMENTED** [review]
Exceptional work! I've left two small suggestions to reduce code duplication a bit. Other than that I've read through and tried to understand everything. I don't think I will have caught small errors if there are any, but the approach seems solid and it's definitely more readable than before.

File: crates/typst-utils/src/lib.rs [hunk 4]
```diff
@@ -16,6 +16,7 @@ pub use self::hash::LazyHash;
 pub use self::pico::PicoStr;
 pub use self::scalar::Scalar;
 
+use std::default::Default;
```
Comment (laurmaedje) [inline crates/typst-utils/src/lib.rs:19]: I think this should not be necessary since it's in the prelude

**Comment by laurmaedje** [comment]
Thank you!
