### PR TITLE
Fix raw bidi text

### LINKED ISSUE #3689: Syntax highlighted raw texts within RTL incorrect direction
### Description

```typ
// Mixing raw
#set text(lang: "he")
#show raw: set text(lang: "en", dir: ltr)
לדוג. `if a == b:` זה תנאי

#set raw(lang:"python")
לדוג. `if a == b:` זה תנאי
```

image

This is due to my PR #3532, since now each section of text is treated individually.

This possible problem was pointed out, but we didn't have an example of where it matters, now we do :laughing: 

> On another note: As implemented, this will individually isolate consecutive segments of text going against the paragraph direction (multiple segments can be forced e.g. by just putting `/**/` between words). Could that be a problem?

_Originally posted by @laurmaedje in https://github.com/typst/typst/issues/3532#issuecomment-1976050396_

Before #3532 for reference (notice the colon on the wrong side):
image

# Possible solutions
- Revert #3532, re-introducing the bug it was trying to solve (code within RTL text will still be broken)
- Add `dir` field to raw, just like text has, and properly handle raw text direction (would adding `lang` as well be necessary, I don't see why but maybe I'm missing something)
- Something completely different?

@laurmaedje would love your input on this, thanks!

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by A-Walrus**
Closes #3689

Uses a `ShowSet` rule to set the lang for raw blocks to English by default, since essentially all non-esoteric languages are in English. Can obviously be easily overridden by the end-user.

Modified my fix from #3532 to use directional embeddings instead of isolates in order to allow multiple consecutive RTL/LTR sections (which is what happens with syntax highlighted text) to combine.

### CODE REVIEW

File: crates/typst/src/layout/inline/mod.rs [hunk 1]
```diff
@@ -450,10 +450,10 @@ fn collect<'a>(
             let prev = full.len();
             let dir = TextElem::dir_in(styles);
             if dir != outer_dir {
-                // Insert "Explicit Directional Isolate".
+                // Insert "Explicit Directional Embedding".
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:453]: According to [Wikipedia](https://en.wikipedia.org/wiki/Bidirectional_text), the Embedding codepoints are legacy and discouraged in favor of the Isolates. Do you know what the concrete difference in semantics is?

Perhaps, we should continue to use the isolates, but apply them on consecutive runs?

Comment (A-Walrus) [reply crates/typst/src/layout/inline/mod.rs:453]: In terms of the difference between them, I got all my info from the spec

> Although the term embedding is used for some explicit formatting characters, the text within the scope of the embedding formatting characters is not independent of the surrounding text. Characters within an embedding can affect the ordering of characters outside, and vice versa. This is not the case with the isolate formatting characters, however. Characters within an isolate cannot affect the ordering of characters outside it, or vice versa. The effect that an isolate as a whole has on the ordering of the surrounding characters is the same as that of a neutral character, whereas an embedding or override roughly has the effect of a strong character.

https://unicode.org/reports/tr9/#Directional_Formatting_Characters

hmm didn't know they were discouraged will have a go using isolates for consecutive runs :+1:

Comment (A-Walrus) [reply crates/typst/src/layout/inline/mod.rs:453]: Had a go at finding consecutive runs, but it really overcomplicates things IMO. You can't just say if the text direction is different then previously I'll add an isolate / a pop, because other elements (especially space) that happen between the text direction change (i.e. after the last RTL but before the next LTR) should not be part of the isolated area, so you have to peek ahead to the next children.

I think that even though they are "discouraged" they are exactly what we need here, otherwise we're pretty much re-implementing parts of the Unicode BIDI algorithm ourselves...

Comment (laurmaedje) [reply crates/typst/src/layout/inline/mod.rs:453]: Ok, let's proceed with this for now. I will think it through again when I'm working on paragraph layout related things in the future.

**Comment by laurmaedje** [comment]
Thanks!
