### PR TITLE
Fix math function tooltips/completions, and add `MathFieldAccess` and `LinkedNode::mode`

### LINKED ISSUE #6312: typst-ide: No autocomplete suggestions in math functions
### Description

When the cursor is inside the arguments of a function in math mode, `typst_ide::autocomplete` gives no suggestions in neither explicit nor implicit mode, although in general math functions compose almost without limitations and completions within one should probably be equivalent to those offered at any other position within math mode.

For example when position is: `$ sqrt(|) $` there are no suggestions. This is also observable in the web app.

If the above sounds acceptable, I'm happy to work on a patch.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by isuffix**
This PR fixes a number of issues with IDE functionality in Typst and adds two major refactorings to simplify future maintenance of these features.

The major refactorings are the addition of the `MathFieldAccess` syntax kind and the `LinkedNode::mode` method. `MathFieldAccess` is meant to further distinguish math from code in the syntax tree (in the same vein as `Ident` vs. `MathIdent`), which both simplifies the implementation of `LinkedNode::mode` and will be useful for future math syntax refactorings. The implementation of `LinkedNode::mode` supersedes PR #7407, but I've changed the implementation to use a data-oriented approach by having the `LinkedNode` method match on an enum, `ModeSearch,` which is only dependent on the `SyntaxKind`.

However, I only implemented the refactorings _after_ having resolved most of the issues via the prior commits. I did this so that I could better understand where those errors were actually coming from and so we could more clearly see the benefits of the refactorings to code clarity without them also affecting behavior. Although the addition of `LinkedNode::mode` did allow for fixing completions for named and spread arguments in math which I couldn't find a way to resolve beforehand.

- Closes #6312
- Resolves a regression added in #7865 where we weren't calling `trace` on identifiers
- Adds many tooltip and completion tests for function calls in math and code
- Adds `SyntaxKind::MathFieldAccess`
- Adds the method `LinkedNode::mode(&self) -> Option<SyntaxMode>`
- Refactors a bunch of stuff in `typst-ide`

### CODE REVIEW

File: crates/typst-syntax/src/kind.rs [hunk 1]
```diff
@@ -520,3 +525,295 @@ impl SyntaxKind {
...
+            SyntaxKind::Strong => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::Emph => ModeSearch::Known(SyntaxMode::Markup),
+            // TODO: Should we treat raw as 'code | markup'?
+            SyntaxKind::Raw => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawLang => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawDelim => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawTrimmed => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::Link => ModeSearch::Known(SyntaxMode::Markup),
+            // TODO: Should we treat labels as 'code | markup'?
+            SyntaxKind::Label => ModeSearch::Known(SyntaxMode::Markup),
```
Comment (isuffix) [inline crates/typst-syntax/src/kind.rs:579]: Both raw text and labels can be included directly in code, but #7407 treated them as markup only, so I wasn't sure if we should change them.

File: crates/typst-eval/src/vm.rs [hunk 2]
```diff
@@ -20,7 +20,8 @@ pub struct Vm<'a> {
     pub flow: Option<FlowEvent>,
     /// The stack of scopes.
     pub scopes: Scopes<'a>,
-    /// A span that is currently under inspection.
+    /// A span that is currently under inspection. If this is `Some`, we're in
+    /// tracing mode, and will record every value  the given span sees.
```
Comment (laurmaedje) [inline crates/typst-eval/src/vm.rs]: `/value  the/value the/`

File: crates/typst-ide/src/tooltip.rs [hunk 3]
```diff
@@ -58,7 +58,9 @@ fn expr_tooltip(world: &dyn IdeWorld, leaf: &LinkedNode) -> Option<Tooltip> {
     }
 
     let expr = ancestor.cast::<ast::Expr>()?;
-    if !expr.hash() && !matches!(expr, ast::Expr::MathIdent(_)) {
+    // We only analyze embeddable code expressions or math expressions that
+    // access variables.
+    if !expr.hash() && !matches!(expr, ast::Expr::MathIdent(_) | ast::Expr::MathCall(_)) {
         return None;
     }
```
Comment (laurmaedje) [inline crates/typst-ide/src/tooltip.rs:72]: I'd suggest this. This would make it simpler to parse mentally imo:
```rust
let analyze =
    expr.hash() || matches!(expr, ast::Expr::MathIdent(_) | ast::Expr::MathCall(_));
if !analyze {
    return None;
}
```

File: crates/typst-ide/src/complete.rs [hunk 4]
```diff
@@ -663,6 +662,11 @@ fn show_rule_recipe_completions(ctx: &mut CompletionContext) {
 }
 
 /// Complete call and set rule parameters.
+///
+/// FUTURE: Make this work math functions. This will require a much deeper
```
Comment (laurmaedje) [inline crates/typst-ide/src/complete.rs]: `/work math/work for math/`

File: crates/typst-eval/src/call.rs [hunk 5]
```diff
@@ -101,11 +108,17 @@ fn eval_math_call(vm: &mut Vm, math_call: ast::MathCall) -> SourceResult<Value>
                 Err(err) => FieldCallee::NonFunc(callee_value, err),
             }
         }
-        ast::MathCallee::FieldAccess(access) => {
+        ast::MathAccess::MathFieldAccess(access) => {
             let target_expr = access.target();
             target_span = target_expr.span();
             let field = access.field();
-            let target = target_expr.eval(vm)?;
+            let target = match target_expr {
```
Comment (laurmaedje) [inline crates/typst-eval/src/call.rs]: This seems a bit duplicate with `Eval for ast::MathFieldAccess<'_>`. What do you think about this change: https://github.com/typst/typst/commit/0096e3c158d35fdde7bb24b7c5898ea460476a79.

Or does it not make sense with planned changes in https://github.com/typst/typst/pull/7866?

(If you think it makes sense, feel free to dissolve this change into your commit structure, no need to keep my commit.)

File: crates/typst-ide/src/complete.rs [hunk 6]
```diff
@@ -51,15 +51,20 @@ pub fn autocomplete(
...
+            || complete_rules(&mut ctx)
+            || complete_params(&mut ctx))
+    {
+        // Only attempt the general completions after the more specific ones.
+        let _ = match mode {
+            SyntaxMode::Markup => complete_markup(&mut ctx),
+            SyntaxMode::Math => complete_math(&mut ctx),
+            SyntaxMode::Code => complete_code(&mut ctx),
+        };
+    }
```
Comment (laurmaedje) [inline crates/typst-ide/src/complete.rs]: how do you feel about short-circuiting with `?`

I'd propose this variant:
```rust
// Already ensures we aren't in a comment.
let mode = ctx.leaf.mode()?;

_ = complete_field_accesses(&mut ctx)
    || complete_open_labels(&mut ctx)
    || complete_imports(&mut ctx)
    || complete_rules(&mut ctx)
    || complete_params(&mut ctx)
    // Only attempt the general completions after the more specific ones.
    || match mode {
        SyntaxMode::Markup => complete_markup(&mut ctx),
        SyntaxMode::Math => complete_math(&mut ctx),
        SyntaxMode::Code => complete_code(&mut ctx),
    };
```

File: crates/typst-ide/src/complete.rs [hunk 7]
```diff
@@ -296,33 +276,7 @@ fn markup_completions(ctx: &mut CompletionContext) {
...
-    }
-
-    // Behind existing interpolated identifier: "$#pa|$".
-    if ctx.leaf.kind() == SyntaxKind::Ident {
-        ctx.from = ctx.leaf.offset();
-        code_completions(ctx, true);
-        return true;
-    }
-
+    debug_assert_eq!(ctx.leaf.mode(), Some(SyntaxMode::Math));
```
Comment (laurmaedje) [inline crates/typst-ide/src/complete.rs]: I'd add an extra blank after this

File: crates/typst-ide/src/complete.rs [hunk 8]
```diff
@@ -898,13 +850,6 @@ fn complete_code(ctx: &mut CompletionContext) -> bool {
         return true;
     }
 
-    // A potential label (only at the start of an argument list): "(<|".
-    if ctx.before.ends_with("(<") {
-        ctx.from = ctx.cursor;
-        ctx.label_completions();
-        return true;
-    }
```
Comment (laurmaedje) [inline crates/typst-ide/src/complete.rs:897]: do we have a test for this working even without the branch here?

File: crates/typst-syntax/src/kind.rs [hunk 9]
```diff
@@ -523,3 +525,298 @@ impl SyntaxKind {
...
+            SyntaxKind::Heading => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::HeadingMarker => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::ListItem => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::ListMarker => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::EnumItem => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::EnumMarker => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::TermItem => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::TermMarker => ModeSearch::Known(SyntaxMode::Markup),
+
+            SyntaxKind::Equation => ModeSearch::Known(SyntaxMode::Math),
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs:591]: I'm not sure this change (and the corresponding whitespace change above) makes sense. See https://github.com/typst/typst/pull/7407#discussion_r2576550495.

File: crates/typst-syntax/src/kind.rs [hunk 10]
```diff
@@ -523,3 +525,298 @@ impl SyntaxKind {
...
+            SyntaxKind::MathAlignPoint => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathCall => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathArgs => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathDelimited => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathAttach => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathPrimes => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathFrac => ModeSearch::Known(SyntaxMode::Math),
+            SyntaxKind::MathRoot => ModeSearch::Known(SyntaxMode::Math),
+
+            SyntaxKind::Hash => ModeSearch::Known(SyntaxMode::Code),
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs:606]: Similarly to the equation, I'm not sure this makes sense since `eval("#", mode: "code")` is an error. In particular, you marked `LeftBracket` as `Parent`. Is it not the exact opposite of `#` in its effect?

File: crates/typst-syntax/src/kind.rs [hunk 11]
```diff
@@ -523,3 +525,298 @@ impl SyntaxKind {
...
+            SyntaxKind::SmartQuote => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::Strong => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::Emph => ModeSearch::Known(SyntaxMode::Markup),
+            // TODO: Should we treat raw as 'code | markup'?
+            SyntaxKind::Raw => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawLang => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawDelim => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::RawTrimmed => ModeSearch::Known(SyntaxMode::Markup),
+            SyntaxKind::Link => ModeSearch::Known(SyntaxMode::Markup),
+            // TODO: Should we treat labels as 'code | markup'?
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs:578]: If we treat what mode it correctly `eval`s as our source of truth, then both raw and label should be parent indeed.

File: crates/typst-syntax/src/kind.rs [hunk 12]
```diff
@@ -523,3 +525,298 @@ impl SyntaxKind {
...
+            SyntaxKind::LeftParen => ModeSearch::Parent, // code | math
+            SyntaxKind::RightParen => ModeSearch::Parent, // code | math
+            SyntaxKind::Comma => ModeSearch::Parent,     // code | math
+            // TODO: Semicolon after code is also embedded like a hash, so this
+            // is incorrect...
+            SyntaxKind::Semicolon => ModeSearch::Parent, // code | math
+            SyntaxKind::Colon => ModeSearch::Parent,     // code | math | markup
+            SyntaxKind::Star => ModeSearch::Parent,      // code | markup
+            SyntaxKind::Underscore => ModeSearch::Parent, // code | math
+            SyntaxKind::Dollar => ModeSearch::Known(SyntaxMode::Math),
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs:620]: this would potentially also be parent then.

File: crates/typst-syntax/src/node.rs [hunk 13]
```diff
@@ -751,6 +752,42 @@ impl<'a> LinkedNode<'a> {
...
+
+    /// Get the [`SyntaxMode`] of this node's parent.
+    ///
+    /// Unlike some other `LinkedNode` methods, this does not treat all trivia
+    /// the same: it returns `None` for comments and returns `Some` for
+    /// whitespace (based on the parent's mode). The only other way this would
+    /// return `None` is when inside a partial tree, i.e. one not rooted in
+    /// `Markup`, `Math`, or `Code`.
+    ///
+    /// Also note that errors inherit the mode of their parent.
```
Comment (laurmaedje) [inline crates/typst-syntax/src/node.rs]: I don't think we need to copy the comment here.

**Review by laurmaedje — COMMENTED** [review]
Nice work! Just a few comments. 

On the mode suggestions for a couple of the "boundary" syntax nodes, I'm not entirely certain, but I feel like it's not quite consistent as is.

File: crates/typst-syntax/src/kind.rs [hunk 14]
```diff
@@ -520,3 +525,298 @@ impl SyntaxKind {
...
+            SyntaxKind::LeftBrace => ModeSearch::Parent, // code | markup
+            SyntaxKind::RightBrace => ModeSearch::Parent, // code | markup
+            SyntaxKind::LeftBracket => ModeSearch::Parent, // code | markup
+            SyntaxKind::RightBracket => ModeSearch::Parent, // code | markup
+            SyntaxKind::LeftParen => ModeSearch::Parent, // code | math
+            SyntaxKind::RightParen => ModeSearch::Parent, // code | math
+            SyntaxKind::Comma => ModeSearch::Parent,     // code | math
+            // TODO: Semicolon after code is also embedded like a hash, so this
+            // is incorrect...
+            SyntaxKind::Semicolon => ModeSearch::Parent, // code | math
```
Comment (isuffix) [inline crates/typst-syntax/src/kind.rs:616]: I added this comment, but I'm now actually unsure if it's correct. If we want to treat a hashtag as code, we must be doing so because we're targeting the position after the hash (`#|`), since the position before the hash (`|#`) would have to be math or markup. If we follow that rule, the position after an embedded semicolon, like `[#123;|]` would again be the mode of its parent. So the current definition should be fine and just needs to be annotated as `code | math | markup`. LMK if that makes sense or not.

File: crates/typst-eval/src/call.rs (hunk 5 above)
Comment (isuffix) [reply crates/typst-eval/src/call.rs]: That's very nice, I'll include it! I think I had a blind spot here due to considering adding mutable methods to math in the future, but that wouldn't actually conflict here.

File: crates/typst-ide/src/complete.rs (hunk 8 above)
Comment (isuffix) [reply crates/typst-ide/src/complete.rs:897]: Looks like no? I can't come up with a way in which this would run without first matching to `complete_open_labels`. Both were initially added by you in this commit: https://github.com/typst/typst/commit/5a6cadefda9a65a83e678e0d541a89bb672962ee, but that didn't add any tests. The `test_autocomplete_ref_function` test was added much later (in #6586), and while it could be matched by this code, `complete_open_labels` gets there first.

**Comment by isuffix** [comment]
I think I've resolved all the non-mode related comments. I also pushed a refactor that didn't change any behavior, but adds `use ModeAfter::*;` and `use SyntaxMode::{...};` statements to `mode_search` to make it easier to read/edit.

For the various mode comments, I think what we really want out of the method is a way to determine the `SyntaxMode` that we would be in immediately after a given node. To me this is justified by the idea that returning anything but `Code` for `#` would be ludicrous; like what would be the use of such a method? I did consider that we could add a `Side` parameter, or maybe define `mode` in terms of a cursor position instead of on the `LinkedNode`, but those all feel a little cumbersome for helping with completions.

This would also resolve what to return when something is embedded with a hash, like `#ident`: we return `Code` because immediately after `ident` you can write `.field` and stay in code mode, which is exactly the completion we want to offer. And while we could make a new distinction between atomic/non-atomic expressions, I don't think it would be worth it.

To clarify this, how would you feel about renaming `LinkedNode::mode` to `LinkedNode::mode_after`? And then `ModeSearch` could be `ModeAfter` and `SytnaxKind::mode_search` could be `mode_after`, although I feel like `parent_mode` could just stay the same.

Finally, for `Label`/`Raw`/`Equation`/`Ident` (and also `Str`), I think we're just missing a new enum variant for `Embeddable` syntax kinds. Those kinds can all exist in either markup or math on their own, but are also available directly in code, or embedded as code into markup/math with a hashtag. And I think the resolution for them is to say that they inherit from their parent _unless_ they're embedded into markup/math with a hashtag. Then with that addition,  for dollar signs we can start to distinguish opening dollar signs from closing ones, where opening dollars will return `Math` (because after them we're in math mode) and closing dollars will return the mode of the overall `Equation`.

**Comment by laurmaedje** [comment]
I think what you say makes sense. I was only thinking about the modes in the abstract, not with their concrete use for completions in mind. I'm on board with the changes.

One thing I don't fully get yet is how `Ident` relates to `Label`/`Raw`/`Equation`. Isn't `Ident` like any other expression? It requires a hash to be in markup, while label/raw/equation don't. In math, idents don't but that would be `MathIdent` then.

**Comment by isuffix** [comment]
`Ident` differs from `Label`/`Raw`/`Equation`/`Str` in that it can't be a _top-level_ expression in markup or math, but unlike say, `Float`, `Ident` is available outside of code mode when in a `Named` kind under `MathArgs`. This makes it somewhat similar to how `Colon` is mainly code-mode, but can be part of markup under `TermItem`. However `Ident` can't just use `Parent` because it can still be embedded with a hashtag like the other embeddable kinds.

**Comment by isuffix** [comment]
Updated with those changes. I also realized that there were issues with a few other kinds like `ContentBlock` (mainly code, but can be markup under `Ref`) and `Space` (needs special handling due to how we use it at the edges of `Equation`), so I updated those and added tests for everything I could think of.

Also, I expanded the `code | math | markup` comments to include the parent kind which produces each other mode. There's a large explanation comment at the top, but LMK it's perhaps too much info or would be too hard to keep up-to-date.

File: crates/typst-syntax/src/kind.rs [hunk 15]
```diff
@@ -520,3 +525,315 @@ impl SyntaxKind {
...
+            Self::Space => Space,      // code/math: part | markup: expr/part
+            Self::Linebreak => Parent, // math/markup: expr
+            Self::Parbreak => Known(Markup),
+            Self::Escape => Parent, // math/markup: expr
+            Self::Shorthand => Known(Markup),
+            Self::SmartQuote => Known(Markup),
+            Self::Strong => Known(Markup),
+            Self::Emph => Known(Markup),
+            Self::Raw => Embeddable,    // code/markup: expr
+            Self::RawLang => Parent,    // code/markup: Raw
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs]: After the `RawLang`, are we really in code or markup? We're still in the raw block after all. So perhaps we could handle this like we handle comments, by returning `None` from `LinkedNode::mode_after.`

The other raw parts are also a bit tricky.

File: crates/typst-syntax/src/kind.rs [hunk 16]
```diff
@@ -520,3 +525,315 @@ impl SyntaxKind {
...
+        // kinds would be too long (otherwise, the list of kinds should be
+        // exhaustive). `expr` is a kind which can be a top-level expression in
+        // its mode, and `part` is a kind which is just a part of an expression.
+        match self {
+            Self::End => Comment,
+            Self::Error => Parent, // code/math/markup
+
+            Self::Shebang => Comment,
+            Self::LineComment => Comment,
+            Self::BlockComment => Comment,
```
Comment (laurmaedje) [inline crates/typst-syntax/src/kind.rs]: Aren't we, in principle, back in the parent mode right after a block comment? Though changing this would also have an effect on the autocomplete changes.

File: crates/typst-ide/src/complete.rs [hunk 17]
```diff
@@ -51,15 +51,20 @@ pub fn autocomplete(
         explicit,
     )?;
 
-    let _ = complete_comments(&mut ctx)
-        || complete_field_accesses(&mut ctx)
+    // Getting the syntax mode also ensures we are not in a comment.
+    let mode = ctx.leaf.mode_after()?;
```
Comment (laurmaedje) [inline crates/typst-ide/src/complete.rs:55]: I wonder if the "mode after" framing will cause any issues when attempting to trigger completions at a position that is not on a node boundary.

File: crates/typst-syntax/src/kind.rs (hunk 15 above)
Comment (isuffix) [reply crates/typst-syntax/src/kind.rs]: I think returning `None` makes sense for the internal kinds. For now, I'll switch to doing so except for the overall `Raw` kind and the closing raw delimiter.

However, you should also know that tinymist has a very similar construct as an `InterpretMode` enum with variants for `Code`/`Math`/`Markup` _and_ `Raw`/`String`/`Comment` (defined in `tinymist-analysis/src/syntax/matcher.rs:316`). If you want, we could try to unify with them by outputting a similar enum, but their code would probably benefit from `mode_after` regardless.

Also note that `Raw` does trigger some special completions for tinymist, but I can't find an instance of them using `String`/`Comment` to produce any particular kind of completion.

File: crates/typst-syntax/src/kind.rs (hunk 16 above)
Comment (isuffix) [reply crates/typst-syntax/src/kind.rs]: I guess we kind of are, but I don't think we can do any better without adding a representation for the delimiter of a comment or changing the whole `mode_after` interface to use cursors instead of whole nodes. So I think it's probably best to just not do anything for this :/

File: crates/typst-ide/src/complete.rs (hunk 17 above)
Comment (isuffix) [reply crates/typst-ide/src/complete.rs:55]: I think there are really only a few edge cases like raw/strings/comments which would be problematic and could be handled by special completions before accessing `mode_after`.

Comment (isuffix) [reply crates/typst-ide/src/complete.rs:55]: But since we don't have any of those completions ourselves, I think it's fine for now?

File: crates/typst-syntax/src/kind.rs (hunk 16 above)
Comment (laurmaedje) [reply crates/typst-syntax/src/kind.rs]: I don't quite follow. What would be wrong about setting `BlockComment` to `Parent`?

Comment (isuffix) [reply crates/typst-syntax/src/kind.rs]: Nothing wrong with it, it would just affect autocompletion if we did.

**Comment by isuffix** [comment]
Rebased off main and updated to return `None` for the bodies of raw text. I also reverted one of the comments in the first commit that would conflict with #8188

**Comment by laurmaedje** [comment]
Thank you!
