### PR TITLE
Fix gradient stroke for line and curve

### LINKED ISSUE #5647: Path stroke gradients do not work as expected
### Description

Tested with `typst 0.12.0 (dhb06dbf9)`. On current master, drawing gradient strokes with `path` got fixed (with the new curve API): it is possible to stroke straight lines (angle 0deg) with a gradient now. But drawing the path flipped, still does not flip the gradient.

The following code:
```typst
#let red-blue = gradient.linear(red, blue, relative: "self")

// Ok
#path((0cm, 0cm), (5cm, 0cm), stroke: red-blue + 5pt)

// Expected blue to red gradient, got red to blue
#path((5cm, 0cm), (0cm, 0cm), stroke: red-blue + 5pt)
```

Results in this rendering:
grafik

### Reproduction URL

_No response_

### Operating system

Web app, Linux

### Typst version

- [ ] I am using the latest version of Typst

### LINKED ISSUE #5705: Border Stroke Gradient Rendering Issue
### Description

The rendering for gradient stroke rendering is currently wrong for right and bottom

```typst
#rect(
  width: 100pt,
  height: 100pt,
  radius: 20pt,
  inset: 0pt,
  fill: black,
  stroke: (
    top: gradient.linear((gray, 0%), (black, 75%), (black, 100%), angle: 90deg) + 3pt,
    right: gradient.linear((gray, 0%), (black, 75%), (black, 100%), angle: 180deg) + 3pt,
    bottom: gradient.linear((gray, 0%), (black, 75%), (black, 100%), angle: 270deg) + 3pt,
    left: gradient.linear((gray, 0%), (black, 75%), (black, 100%), angle: 0deg) + 3pt,
  )
)
```

Image

### Reproduction URL

_No response_

### Operating system

Windows

### Typst version

- [x] I am using the latest version of Typst

### LINKED ISSUE #6068: Gradients on `curve` elements don't use the correct bounding box when last segment is `curve.line`
### Description

Consider
```typ
#curve(  
  curve.line((40pt, 40pt)),
  stroke: gradient.linear(blue, red).sharp(2)
)
```
Due to the sharp gradient, we expect a line that is half red and half blue but actually it is rendered 
- entirely blue with `png` and
- entirely red with `pdf` and `svg` export. 

The issue **does not occur** with
- `path`
  ```typ
  #path(
    (0pt, 0pt),
    (40pt, 40pt),
    stroke: gradient.linear(blue, red).sharp(2)
  )
  ```
- when using a `curve.quad` or `curve.cubic` element, e.g., 
  ```typ
  #curve(  
    curve.quad(none, (40pt, 40pt)),
    stroke: gradient.linear(blue, red).sharp(2)
  )
  ```

Note that this has nothing to do with sharp gradients, they are just better to demonstrate the issue. 

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by eltos**
Fixes issues with gradient strokes for lines and curves:
- Take the stroke width into account when calculating the bounding box to avoid zero-sized boxes
- Avoid mirroring the gradient for negative bounding box sizes when the angle is outside the first quadrant
- Fixes #6068
- Fixes #5705
- Closes #5647 as "expected behaviour", since the gradient is now always drawn according to the angle specified. The previous behaviour of line strokes using a mirrored gradient when end is left of start was IMHO confusing, especially for gradient angles other than 0deg, and anyhow not consistently applied to paths/curves. See output of _gradient-line-stroke_ test below for the comparison of this behaviour before/after.

### Tests added

_Left / right shows before / after this PR. PDF screenshots are from Adobe Acrobat (report.html does not render them correctly with my firefox)_

**issue-6068-curve-stroke-gradient**
PNG
grafik
SVG
canvas
PDF
canvascanvas

**issue-5705-gradient-border-stroke paged**
PNG

SVG

PDF

_In the test images below, each "star" consists of lines/curves at different angles, all using the same stroke gradient._

**gradient-line-stroke**
PNG

SVG

PDF
grafik

**gradient-curve-stroke**
PNG

SVG

PDF
canvas

**gradient-curve-stroke-quad**
PNG

SVG

PDF
canvas

### CODE REVIEW

File: crates/typst-library/src/visualize/curve.rs [hunk 1]
```diff
@@ -547,6 +523,10 @@ impl Curve {
     /// When this curve is stroked with `stroke`, would the stroke contain
     /// `point`?
     pub fn stroke_contains(&self, stroke: &FixedStroke, needle: Point) -> bool {
+        Shape::contains(&self.to_kurbo_stroke(stroke), point_to_kurbo(needle))
```
Comment (saecki) [inline crates/typst-library/src/visualize/curve.rs]: Could you prefix `Shape` with `kurbo::` for consistency and use an underscore import: `use kurbo::Shape as _`, so it's only to bring the trait methods in scope.

File: crates/typst-pdf/src/paint.rs [hunk 2]
```diff
@@ -65,13 +65,31 @@ fn convert_paint(
...
+    let mut size = Size::zero();
+    let mut offset = Point::zero();
+    if let Some(s) = shape {
+        size = s.geometry.bbox_size();
+
+        // Edge cases for strokes.
+        if matches!(s.geometry, Geometry::Line(..) | Geometry::Curve(..)) {
+            (offset, size) = s.geometry.bbox_size_with_stroke(s.stroke.as_ref());
+            // avoid mirroring gradient if line angle results in negative sizes
+            if size.x.signum() < 0.0 {
```
Comment (saecki) [inline crates/typst-pdf/src/paint.rs]: ~Does the `signum` handle a case I'm not aware of? Negative inifinity and signed `-0.0` should also be handled by a direct comparison.~

With the changes to `bbox_size_with_stroke` these extra checks could be completely removed.

File: crates/typst-library/src/visualize/shape.rs [hunk 3]
```diff
@@ -423,4 +424,32 @@ impl Geometry {
             Self::Curve(curve) => curve.bbox_size(),
         }
     }
+
+    /// The bounding box offset and size
+    /// taking the stroke width of the shape into account
+    pub fn bbox_size_with_stroke(&self, stroke: Option<&FixedStroke>) -> (Point, Size) {
```
Comment (saecki) [inline crates/typst-library/src/visualize/shape.rs]: I feel like this function should be renamed to `bbox_with_stroke` and return a `Rect`. Since it's a bounding box, the size should never be negative, and that would remove the extra code path in `typst-pdf` to avoid mirrored gradients.

File: crates/typst-library/src/visualize/shape.rs [hunk 4]
```diff
@@ -423,4 +424,32 @@ impl Geometry {
...
+        let bbox = self.bbox_size();
+        let stroke_width = stroke.map(|s| s.thickness).unwrap_or(Abs::zero());
+        match self {
+            Self::Line(line) => {
+                let a = Angle::atan2(line.y.to_raw(), line.x.to_raw());
+                let padding = Size::new(
+                    line.x.signum() * stroke_width * 0.5 * a.sin().abs(),
```
Comment (saecki) [inline crates/typst-library/src/visualize/shape.rs]: Does this handle square stroke caps?

File: crates/typst-pdf/src/text.rs [hunk 5]
```diff
@@ -33,16 +32,17 @@ pub(crate) fn handle_text(
...
-            paint::convert_stroke(gc, s, true, surface, fc.state(), Size::zero())
-        }) {
-            Some(stroke?)
-        } else {
-            None
-        };
+    let stroke = if let Some(stroke) = t
+        .stroke
+        .as_ref()
+        .map(|s| paint::convert_stroke(gc, s, true, surface, fc.state(), None))
```
Comment (saecki) [inline crates/typst-pdf/src/text.rs]: I think moving the code from the `map` inside the if let would be more readable.

File: crates/typst-library/src/visualize/shape.rs (hunk 3 above)
Comment (eltos) [reply crates/typst-library/src/visualize/shape.rs]: This could be changed, but the other bbox methods also return negatively sized bboxes. We should keep it consistent, shouldn't we?

Changing this would also disable the mirroring behaviour for negatively sized rects, see #6597. I'm fine with that, but it should be considered. What do you think?

File: crates/typst-pdf/src/text.rs (hunk 5 above)
Comment (eltos) [reply crates/typst-pdf/src/text.rs]: I only changed `Size::zero()` for `None` here, rest was `cargo fmt`. But I can do that as refactor.

Comment (saecki) [reply crates/typst-pdf/src/text.rs]: Yeah that would be appreciated :)
The line-wrap heuristics of `rustfmt` are a bit unfortunate sometimes.

File: crates/typst-library/src/visualize/shape.rs (hunk 3 above)
Comment (saecki) [reply crates/typst-library/src/visualize/shape.rs]: > This could be changed, but the other bbox methods also return negatively sized bboxes. We should keep it consistent, shouldn't we?

I think the only other `bbox` and `bbox_size` methods are for `Curve` and there `bbox_size` is a wrapper of the `bbox` method, which always computes a rectangle with positive dimensions. 

> Changing this would also disable the mirroring behaviour for negatively sized rects, see https://github.com/typst/typst/issues/6597. I'm fine with that, but it should be considered. What do you think?

Hmm I see, currently this seems to be handled a little bit differntly in every export. The whole concept of negative sizes for bounding boxes seems to be somewhat of a pain point.

Maybe we can move the logic into `typst-library` and  introduce a `BBox` type to make this more robust. It could have a `Point` and `Size` internally and explicit accessors to either get a positive `Rect` with `min` and `max` coordinates, or the possibly negative `Size` and the offset `Point`.
For `Curve` the bounding box is already always positive, for `Line` we could just use this code, the other ones would stay the same https://github.com/typst/typst/blob/88356d0b708393dc96d8dd6ac88d96cc6e190e06/crates/typst-library/src/visualize/shape.rs#L404

Then we could get rid of the `bbox_size`, and looking at it more closely, I think we should remove `bbox_size_with_stroke` and instead make `Geometry::bbox()` take an optional `stroke` parameter, like you added for `Curve::bbox()`. Finally we could add a `Shape::bbox()` method, which uses the shape's `stroke` field, since that seems to always be passed anyway.

This refactor can be done in a follow-up PR, it just feels like this would remove a lot of the complications.

Comment (saecki) [reply crates/typst-library/src/visualize/shape.rs]: Or maybe we could remove handling of negative dimensions alltogether, depending on the outcome of https://github.com/typst/typst/issues/7901

File: crates/typst-library/src/visualize/shape.rs (hunk 4 above)
Comment (eltos) [reply crates/typst-library/src/visualize/shape.rs]: I have update this to use kurbo in order to handle both square and round caps. Also added a test for it:

File: crates/typst-library/src/visualize/shape.rs (hunk 3 above)
Comment (eltos) [reply crates/typst-library/src/visualize/shape.rs]: > Changing this would also disable the mirroring behaviour for negatively sized rects

I was wrong, this behaviour originates from `bbox_size` not `bbox_size_with_stroke`. Hence, I applied the rename, signature change and merge with `bbox` as you initially proposed. Further changes touching `bbox_size` can be kept for another PR, depending on outcome of #7901.

File: crates/typst-pdf/src/paint.rs (hunk 2 above)
Comment (eltos) [reply crates/typst-pdf/src/paint.rs]: done

**Comment by eltos** [comment]
@saecki ready for 2nd review

File: crates/typst-pdf/src/paint.rs [hunk 6]
```diff
@@ -65,23 +65,35 @@ fn convert_paint(
...
-    // Edge cases for strokes.
-    if size.x.is_zero() {
-        size.x = Abs::pt(1.0);
-    }
+    let mut bbox = if let Some(s) = shape {
+        match s.geometry {
+            Geometry::Line(_) | Geometry::Curve(_) => s.geometry.bbox(s.stroke.as_ref()),
+            // Special handling for fill of rectangles (mirrors gradients for negative sizes)
+            Geometry::Rect(_) => {
+                Rect::from_pos_size(Point::zero(), s.geometry.bbox_size())
```
Comment (saecki) [inline crates/typst-pdf/src/paint.rs]: The documentation on `Rect` says that `min` is always smaller than `max`, and the `from_pos_size` function doesn't check that. Maybe this could return a `Point` and `Size` tuple for now, so that we don't misuse the documented API of `Rect`.
The same also applies to the code in `typst-svg`.

Comment (saecki) [inline crates/typst-pdf/src/paint.rs]: ~~I've just noticed that by not passing the stroke, the bbox will be wrong for rectangles created by the `typst_layout::shapes::simple_rect` function such as:~~

```typ
#rect(
  width: 100pt,
  height: 100pt,
  stroke: gradient.linear(green, black, yellow, angle: 90deg).sharp(8) + 20pt,
)
```

~~The gradient is not spreading to the edge of the stroke (the weird clipping in the converted PDF is an issue that should be fixed in a newer hayro version)
[report.html](https://github.com/user-attachments/files/25694315/report.html)~~

~~So essentially the special handling for rectangles also has to check if the paint is converted for the stroke or the fill of the rectangle shape.~~

EDIT: It's probably desirable to have the same transform as the rect fill here, so let's just leave this as is :thinking:

File: crates/typst-render/src/shape.rs [hunk 7]
```diff
@@ -67,43 +67,28 @@ pub fn render_shape(canvas: &mut sk::Pixmap, state: State, shape: &Shape) -> Opt
...
             let dash = dash.as_ref().and_then(to_sk_dash_pattern);
-
-            let bbox = shape.geometry.bbox_size();
-            let offset_bbox = if !matches!(shape.geometry, Geometry::Line(..)) {
-                offset_bounding_box(bbox, *thickness)
-            } else {
-                bbox
-            };
-
+            let bbox = shape.geometry.bbox(shape.stroke.as_ref());
```
Comment (saecki) [inline crates/typst-render/src/shape.rs]: (This comment should go on line 44, but I can't add comments to lines not modified in this PR)

I've found another issue only present in `typst-render` for rectangles that don't have a radius. This is the `issue-5705-gradient-border-stroke` test without the `radius`:

```
#rect(
  width: 100pt,
  height: 100pt,
  stroke: (
    top: gradient.linear(green, black, yellow, angle: 90deg) + 20pt,
    right: gradient.linear(green, black, yellow, angle: 180deg) + 20pt,
    bottom: gradient.linear(green, black, yellow, angle: 270deg) + 20pt,
    left: gradient.linear(green, black, yellow, angle: 0deg) + 20pt,
  )
)
```

[report.html](https://github.com/user-attachments/files/25694919/report.html)

File: crates/typst-pdf/src/paint.rs (hunk 6 above)
Comment (eltos) [reply crates/typst-pdf/src/paint.rs]: Okay, reverted to use `Point` and `Size` again as in the initial commit.

File: crates/typst-render/src/shape.rs (hunk 7 above)
Comment (eltos) [reply crates/typst-render/src/shape.rs]: Fixed and test updated

grafik

**Comment by eltos** [comment]
@saecki ready for 3rd review

> Thanks! And sorry for the delay (we had quite a busy week).

No worries. I look forward to watching the talks from the meeting on your YouTube channel.

File: crates/typst-pdf/src/paint.rs (hunk 6 above)
Comment (eltos) [reply crates/typst-pdf/src/paint.rs]: I thought about it again, and I think for consistency it would actually be better to use different bboxes, i.e. use the tight bbox-without-stroke for the fill gradient, and the extended bbox-with-stroke for the stroke gradient.
Here's an example with a `rect`, `rect(radius: 20pt)`, `curve` and `circle`:

| Before PR | Current state of PR | Proposed |
|-|-|-|
|before|fc70e77|proposed

Reasoning:
- Before PR: uses bbox-without-stroke for both fill and stroke, this breaks gradients on lines, curves etc. where the bbox size collapses
- Current state of PR: Uses bbox-with-stroke for strokes on lines and curves but also changes bbox for some fills. This leads to inconsistency because of the special handling for rects. For round rects the situation is more complex as fill and strokes are handled separately and the codepath that generates the fill is not aware of the strokes (I think the reason being that strokes can be different for the four edges). So using the bbox-with-strokes for the fill is currently not possible.
- Proposed: Keep using the bbox-without-stroke for fills as before, and use bbox-with-stroke for all strokes (even for `rect` to handle zero-sized rects with strokes). This results in different bboxes for fill and stroke, but is consistent across shapes, predictable and backwards compatible with respect to gradient fills.

Note that the test "gradient-fill-and-stroke", which with the current state of the PR still passes, would change with the proposed version.
canvas
As it's a bit difficult to see, here a variant with a sharp gradient and different colors:




It's a design decision (at least until linear gradient start/end point can be controlled, see https://github.com/typst/typst/issues/2282). 
Let me know what you think.

Comment (saecki) [reply crates/typst-pdf/src/paint.rs]: > Note that the test "gradient-fill-and-stroke", which with the current state of the PR still passes, would change with the proposed version.

That's what I thought of when I wanted to dismiss this comment, but I didn't think of the other cases where this already happens because the rectangle is decomposed into different shapes.

> I thought about it again, and I think for consistency it would actually be better to use different bboxes, i.e. use the tight bbox-without-stroke for the fill gradient, and the extended bbox-with-stroke for the stroke gradient.

I agree, we definitely either want the state `Before PR` or the `Proposed` one, not the in-between we currently have. Since the `Before PR` state wouldn't allow properly and consistently dealing with gradients on strokes, I think it's better to opt for your proposed changes.

Maybe the use case of `gradient-fill-and-stroke` can be revisited together with `relative` gradients and tilings at some point. But at least for the example shown, just removing the stroke and using an `outset` should be enough to replicate it.

Comment (eltos) [reply crates/typst-pdf/src/paint.rs]: Okay, I applied the proposed changes and replaced the `gradient-fill-and-stroke` test




Also did some more refactoring, including what you suggested earlier:
> Then we could get rid of the bbox_size, and [...]
> Finally we could add a Shape::bbox() method, which uses the shape's stroke field, since that seems to always be passed anyway.
> This refactor can be done in a follow-up PR, it just feels like this would remove a lot of the complications.

File: crates/typst-library/src/visualize/curve.rs [hunk 8]
```diff
@@ -475,46 +475,22 @@ impl Curve {
...
+        Rect::new(
+            Point::new(Abs::raw(bbox.x0), Abs::raw(bbox.y0)),
+            Point::new(Abs::raw(bbox.x1), Abs::raw(bbox.y1)),
+        )
     }
 
     /// Computes the size of the bounding box of this curve.
     pub fn bbox_size(&self) -> Size {
-        self.bbox().size()
+        self.bbox(None).size()
```
Comment (saecki) [inline crates/typst-library/src/visualize/curve.rs]: I think we can now completely remove the `bbox_size` method

Comment (eltos) [reply crates/typst-library/src/visualize/curve.rs]: Done with ce72e88c39065a5b7def4d81645ad9f1f23c7116

**Comment by laurmaedje** [comment]
Thank you!
