### PR TITLE
Fix excessive sampling of linear gradients in PDF and SVG

### LINKED ISSUE #6326: gradient.linear with sharp will alias depending on space used
### Description

When viewing a linear gradient inside a rectangle and using the sharp function, aliasing between the colors can show up if the `space` argument is used.

Version
```shell-session
$ typst --version
typst 0.13.1 (unknown hash)
```

Code

```typst
#rect(width: 100%, height: 5em, fill: gradient.linear(
  (oklch(51%, 0.208963, 29.2339deg)),
  (oklch(70%, 0.204259, 43.4910deg)),
  (oklch(81%, 0.168100, 76.7800deg)),
  (oklch(60%, 0.175100, 147.560deg)),
  (oklch(60%, 0.141400, 241.380deg)),
  (oklch(46%, 0.194300, 288.710deg)),
).sharp(6))

#rect(width: 100%, height: 5em, fill: gradient.linear(
  space: color.oklch,
  (oklch(51%, 0.208963, 29.2339deg)),
  (oklch(70%, 0.204259, 43.4910deg)),
  (oklch(81%, 0.168100, 76.7800deg)),
  (oklch(60%, 0.175100, 147.560deg)),
  (oklch(60%, 0.141400, 241.380deg)),
  (oklch(46%, 0.194300, 288.710deg)),
).sharp(6))
```

Screenshot from Zathura PDF viewer

Image

Screenshot from Okular PDF viewer

Image

For some reason this phenomena does not show up in typst.app.

### Reproduction URL

https://typst.app/project/rnzQ5cDvguAygjlMJI6Ti9

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

### LINKED ISSUE #7365: Excessive sampling of linear gradients in PDF
After rebasing my `test-suite` branch, I noticed some PDF tests getting noticable slower. I pinpointed it to this PR: #7326

This specific test now takes up twice the amount of time:
```typ
--- gradient-math-misc ---
// Test miscellaneous
#show math.equation: set text(fill: gradient.linear(..color.map.rainbow))
#show math.equation: box

$ hat(x) = bar x bar = vec(x, y, z) = tilde(x) = dot(x) $
$ x prime = vec(1, 2, delim: "[") $
$ sum_(i in NN) 1 + i $
$ attach(
  Pi, t: alpha, b: beta,
  tl: 1, tr: 2+3, bl: 4+5, br: 6,
) $
```

The gradient code in `typst-pdf` generates 31 samples between every stop of a gradient. Since the `rainbow` gradient already has a lot of stops, this seems to be the culprit. Maybe we can choose the number of samples based on the distance of the stops and or distance of the hue instead? In the rainbow case I think it would be fine to basically omit any extra sampled stops.

### PR DESCRIPTION
**Pull request by eltos**
### Description
**Commit a82dce9d52a83da6e9853b98e1e00d23a7697dbc**
Fixes duplicating stops at equal offset during interpolation, which caused sharp gradients in PDF to become blurry.
Also fixes duplicating stops in SVG where both stops of the (overlapping) window strides were added.
This results in visual changes (fixes) to the tests containing sharp gradients (see examples below).

- [x] Fixes #6326  
      Maybe also https://github.com/typst/typst/issues/6968, to be clearified  
	  Contributes to https://github.com/typst/typst/issues/6359

**Commit ba121d92ec65ff01840a1311db441b52f871b447**
Instead of always inserting a fixed number of in-between-stops (30 for PDF, 256/len for SVG), only insert actually required stops.
How many stops are required is determined by comparing the linearly rgb-interpolated color with the actual color at the midpoints, iteratively subdividing the distance between stops until the error falls below a threshold.
The threshold of 0.001 used results in no visible change. 
I also tested with 0.01 where there are very small almost unnoticable changes (see examples below). 
Since the step 0.001 to 0.01 reduces the size only little, I decided to use 0.001 in the end, but this can be adjusted if desired.

- [x] Fixes #7365
      Contributes to https://github.com/typst/typst/issues/6359

### Size statistics for `cargo testit gradient`

| | Before this PR | Duplication fix | **With th=0.001** | (With th=0.01)
|-|-|-|-|-|
| Stop count bloat factor in PDF export       |28.7   |16.2   |**15.0**   |14.6
| total size of PDF files with gradient tests |67.9 MB|63.2 MB|**2.9 MB** |2.7 MB
| Stop count bloat factor in SVG export       |30.2   |29.8   |**4.4**    |1.9
| total size of SVG files with gradient tests |13.1 MB|11.3 MB|**10.5 MB**|10.4 MB

_Stop count bloat factor denotes the number of stops after the interpolation, compared to the number of stops of the original gradient (mean of factors for all tests)_

### Changes (examples)

Changes due to sharp gradient fix:

gradient-linear-stroke-relative-parent first_commit
curve-stroke-gradient-sharp first_commit
issue-6680-gradient-linear-with-aspect-correction first_commit

---------

Changes in case of th=0.01:

grafik

grafik
grafik

### CODE REVIEW

**Comment by LaurenzV** [comment]
I've mentioned this somewhere else, but in case it hasn't been tried, I would strongly suggest trying to use the [color](https://crates.io/crates/color) crate and the [gradient](https://docs.rs/color/latest/color/fn.gradient.html) method to create the optimal number and location of stops to approximate the color in SRGB. I don't know the theory behind it, but I think they use some more advanced approach to determine the best approximation for the given color space. This won't work for CMYK unfortunately, so we would need fallback behavior there, but I believe all other color spaces are supported.

**Comment by eltos** [comment]
Thank you, I looked at how they do it and basically followed the same algorithm: bisecting the gradient until the Euclidean difference between the rgb-linearly interpolated midpoint color and the midpoint actual color between two stops falls below a threshold. I decided against using the color create to avoid adding it as dependency, to avoid the copying and type conversion necessary to call that method, to avoid the non-CMYK restriction and because in the end it's a rather simple algorithm.

**Comment by LaurenzV** [comment]
Fair enough!

**Comment by laurmaedje** [comment]
@eltos Is this ready for review? Since this and your other PR are still marked as draft.

**Comment by eltos** [comment]
Not yet, there is a similar stop duplication behaviour in SVG export which I plan to cover, too. Please bear with me, I'll notify you once I come to it and the PR is ready.

**Comment by laurmaedje** [comment]
Sure, no rush, it's just that sometimes people open a draft PR when they're actually waiting for a review, so I wanted to double check.

**Comment by eltos** [comment]
@laurmaedje PR ready for review. SVG handling added and threshold lowered to 0.001, see details in updated PR description.

File: crates/typst-library/src/visualize/gradient.rs [hunk 1]
```diff
@@ -819,6 +819,70 @@ impl Gradient {
...
 
+    /// Generates additional stops to replicate a gradient in
+    /// rgb color space interpolation by bisecting
+    pub fn generate_intermediate_stops_for_rgb_interpolation(
+        &self,
+        first: GradientStop,
+        second: GradientStop,
+    ) -> impl Iterator<Item = (Color, Ratio)> {
+        let threshold = 0.001;
+        let max_subdivisions = 64;
```
Comment (saecki) [inline crates/typst-library/src/visualize/gradient.rs]: I think making these `const`s would improve readability. They could just stay here in the function.

Comment (eltos) [reply crates/typst-library/src/visualize/gradient.rs]: done

Comment (saecki) [reply crates/typst-library/src/visualize/gradient.rs]: Perfect, thanks!

**Comment by laurmaedje** [comment]
Thank you!
