### PR TITLE
Fix list indent when starting at an open bracket

### LINKED ISSUE #5675: List indent is handled wrong in content blocks
### Description

The indent handling of lists in content blocks regressed.

<table>

<thead>
  <td>Code</td>
  <td>0.12 output</td>
  <td>Dev output</td>
</thead>

<tbody>
<tr>
  <td>

```typ
// List nested in content block
// Both are indented equally
#[- A
  - B]
```

  </td>

<td>
image
</td>

<td>
image
</td>
</tr>
<tbody>

</table>

I didn't bisect, but probably due to #5310?

cc @wrzian 

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by wrzian**
Fixes #5675

Test fails before, passes after.

### CODE REVIEW

File: crates/typst-syntax/src/parser.rs [hunk 1]
```diff
@@ -1605,10 +1605,12 @@ impl AtNewline {
...
-            AtNewline::RequireColumn(min_col) => match column {
-                Some(column) => column <= min_col,
-                None => false, // Don't stop if we had no column.
-            },
+            AtNewline::RequireColumn(min_col) => {
+                // Don't stop if this newline doesn't start a column (this may
+                // be checked on the boundary of lexer modes, since we only
+                // report a column in Markup).
+                column.is_some_and(|column| column <= min_col)
+            }
```
Comment (wrzian) [inline crates/typst-syntax/src/parser.rs:1613]: Note that this was just a small relevant aesthetic change, and shouldn't affect behavior.

**Comment by laurmaedje** [comment]
Thanks!
