### PR TITLE
Show aliases of citation styles in docs and completions

### LINKED ISSUE #6669: Show aliases of citation styles in the docs
### Description

Some citation styles have multiple names, a main display name, and one or more aliases.

Currently, the docs site says aliases are listed as a dedicated style, but in fact they are not listed anywhere.

> <html><body>

"institute-of-electrical-and-electronics-engineers" | IEEE
-- | --

</body>
</html>

We could change it to
> <html><body>

"institute-of-electrical-and-electronics-engineers" | IEEE (alias: "ieee")
-- | --

</body>
</html>

https://github.com/typst/typst/blob/59243dadbb2e9f5fc4fd55b0dbfaca6496caf761/crates/typst-library/src/model/bibliography.rs#L126-L131

https://github.com/typst/typst/blob/59243dadbb2e9f5fc4fd55b0dbfaca6496caf761/crates/typst-library/src/model/bibliography.rs#L439-L447

https://discord.com/channels/1054443721975922748/1399326777540608041/1399349305629741081

---

Besides, it is known `"alphanumeric"` is listed in both `cite` and `bibliography`, but not actually suitable for `bibliography`.
However, I don't think it worth fixing.

> Because `CiteElem` and `BibliographyElem` both use this same type, they share the same list

> Then I think it's fine to just ignore the difference between `cite` and `bibliography`. Since no one would normally want to use alphanumeric for `bibliography`, even if someone uses it accidentally (e.g., select the wrong item in auto completion), typst still provides a lovely error message. The difference only matters when  [enumerating all styles](<https://forum.typst.app/t/the-last-resort-for-correcting-the-format-of-bibliography-for-60-styles/5303/4?u=y.d.x>), which is quite rare.

https://discord.com/channels/1054443721975922748/1399326777540608041/1399364343296036964

### PR DESCRIPTION
**Pull request by YDX-2147483647**
Some citation styles have multiple names, a main name, and one or more aliases.
Currently, [the docs site says aliases are listed as a dedicated style](https://typst.app/docs/reference/model/bibliography/#parameters-style), but in fact they are not listed anywhere.
Futhermore, they are missing in auto-completions.

This PR will add those aliases to docs and completions.

This PR #6696 resolves #6669.
(Nice numbers :-)

## Example

`apa`, `ieee`, etc. will now be included in the JSON generated by typst-docs:

```diff
  {
    "string": "american-psychological-association",
    "details": "<p>American Psychological Association 7th edition</p>"
  },
+ {
+   "string": "apa",
+   "details": "<p>A short alias of <code>american-psychological-association</code></p>"
+ },
```

Before:

| Variant | Details |
|--------|--------|
| `"american-psychological-association"` | American Psychological Association 7th edition |

After:

| Variant | Details |
|--------|--------|
| `"american-psychological-association"` | American Psychological Association 7th edition |
| `"apa"` | A short alias of `american-psychological-association` |

You can verify it by running `cd docs && cargo run 2>/dev/null | rg '"apa"' --context 5`.

### CODE REVIEW

File: crates/typst-library/src/model/bibliography.rs [hunk 1]
```diff
@@ -438,13 +438,40 @@ pub enum CslSource {
     Normal(DataSource),
 }
 
+/// All possible names and their short documentation for `ArchivedStyle`, including aliases.
+static ARCHIVED_STYLE_NAMES: OnceLock<Vec<(&&str, &'static str)>> = OnceLock::new();
```
Comment (laurmaedje) [inline crates/typst-library/src/model/bibliography.rs]: the static could be moved directly inside `input()` to keep it local to where it's used.

Comment (laurmaedje) [reply crates/typst-library/src/model/bibliography.rs]: also, I think this could just be a `LazyLock`.

Comment (YDX-2147483647) [reply crates/typst-library/src/model/bibliography.rs]: Thanks! just updated that. I should have read docs.rs/std first.

**Comment by laurmaedje** [comment]
Thanks!
