### PR TITLE
Resolve spacing before comparing

### LINKED ISSUE #1238: Wrong block spacing comparison with different font sizes when specified in em
### Description

When font sizes are different and blocks have spacing specified in `em` it compares just spacing value without taking into account font size.

```
#grid(
  columns: (1fr, 1fr),
  {
    text(size: 40pt, block(below: 1em, "BIG"))
    text(size: 20pt, block(above: 1em, "SMALL"))
  },
  {
    text(size: 40pt, block(below: 1em, "BIG"))
    text(size: 20pt, block(above: 1.1em, "SMALL"))
  }
)
```

Screenshot 2023-05-17 at 17 59 33

### Reproduction URL

_No response_

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by EpicEricEE**
Fixes #1238 

When collapsing adjacent spacing elements, the corresponding font sizes were not considered, which could result in `1em` being larger than `1.1em`. I decided to remove the `PartialOrd` trait from Spacing as it feels a bit misleading, however, if you think it should stay, that can of course be reverted.

> [!NOTE]
> Unfortunately, collapsing a relative-sized spacing as `v(30%)` with an absolute-sized one is still not done properly, as the relative size is only resolved at a later layout step.

### CODE REVIEW

File: crates/typst-library/src/layout/spacing.rs [hunk 1]
```diff
@@ -64,9 +62,19 @@ impl Behave for HElem {
         }
     }
 
-    fn larger(&self, prev: &Content) -> bool {
-        let Some(prev) = prev.to::<Self>() else { return false };
-        self.amount() > prev.amount()
+    fn larger(
+        &self,
+        prev: &(Content, Behaviour, StyleChain),
```
Comment (EpicEricEE) [inline crates/typst-library/src/layout/spacing.rs:67]: This type is probably not ideal, especially because `Behaviour` is not used. I only used it because it made calling the function easier.

**Comment by laurmaedje** [comment]
Do you know what exactly happened in the reference images that changed?

**Comment by EpicEricEE** [comment]
The spacing between a raw element and a paragraph consists of two weak spacings: the "below" of the raw block and the "above" of the paragraph block. Both are by default set to 1.2em. The raw element sets its font size to 0.8em, which decreases the absolute "below" spacing. Previously, typst would not realize that the spacing values are different and thus use the first one added, which is the smaller "below" spacing from the raw element. The new images have equal spacing around raw elements instead of more above than below.

The same happens when a higher-level heading is preceded by one with lower level as they have different font sizes.

**Comment by laurmaedje** [comment]
Okay thanks, that makes sense.
