### PR TITLE
Fix newline parsing behavior in code mode

### LINKED ISSUE #490: Parser doesn't allow comments after `if` body and before `else`
MWE:
```typst
#let typeset(body, key: none) = {
    if body == none { empty }
    else if type(body) == "array" and body.len() == 0 { empty }
    // else if type(body) != "content" { empty }
    else { body }
}
```

Compiler output:
```text
error: unexpected keyword `else`
  ┌─ teste.typ:5:8
  │
5 │         else { body }
  │         ^^^^
```

### LINKED ISSUE #3746: Chained method calls should be able to be commented out
### Description

I'm starting to do much larger and more functional functions, and sometimes need to comment out a filter or similar chained method off array, but it doesn't work and I have to delete the line to get the outcome I'm after

Example:

```
#let demo = {
  range(1, 20)
  // .filter(calc.even)
  .map(x => str(x, base: 16))
}

#demo
```

Expected outcome: the filter method is omitted, the output is just the range shown in hex
Actual: error 
```
This markup in “main.typ”…
…caused this problem:
Unexpected dot
```

### Reproduction URL

_No response_

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Leedehai**
Let the lexer allow comments mixed in. Fixes #3746. Also fixes #490.

### CODE REVIEW

File: crates/typst-syntax/src/lexer.rs [hunk 1]
```diff
@@ -27,9 +27,9 @@ pub(super) struct Lexer<'s> {
 pub(super) enum LexMode {
     /// Text and markup.
     Markup,
-    /// Math atoms, operators, etc.
+    /// Math mode, i.e. those in `$ .. $`.
     Math,
-    /// Keywords, literals and operators.
+    /// Code mode, e.g. `#let a = 1`, `#{ ... }`.
```
Comment (laurmaedje) [inline crates/typst-syntax/src/lexer.rs:32]: This is a bit misleading, since `#let ..` is an embedded markup expression. I'd prefer if the doc comments were reverted.

File: crates/typst-syntax/src/lexer.rs [hunk 2]
```diff
@@ -121,6 +124,17 @@ impl Lexer<'_> {
         }
     }
 
+    pub fn next_non_trivia(&mut self) -> SyntaxKind {
```
Comment (laurmaedje) [inline crates/typst-syntax/src/lexer.rs:127]: I wonder whether this method should really be on the lexer or rather be specific to the parser implementation. The reasoning is that this method is easy to misuse: It should only ever be called on a cloned lexer since it will otherwise discard tokens, messing up the syntax tree.

File: tests/typ/bugs/newline-mode.typ [hunk 3]
```diff
@@ -22,3 +22,53 @@
 else {
   ("1", "2")
 }
+
+---
+#{
+  "hi 1"
+
+    .clusters()
+}
```
Comment (laurmaedje) [inline tests/typ/bugs/newline-mode.typ:31]: I know that the test existed before, but would you mind rewriting the new test cases that don't strictly need an image to use `test(..)` assertions instead? I want new tests to make more use of direct assertions compared to reference images, as they are smaller and easier to compare/review.

```suggestion
#test({
  "hi 1"

    .clusters()
}, ("h", "i", " ", "1"))
```

File: crates/typst-syntax/src/lexer.rs (hunk 2 above)
Comment (Leedehai) [reply crates/typst-syntax/src/lexer.rs:127]: I was torn tbh.. but the reason of abuse-proof here makes sense!

**Comment by laurmaedje** [comment]
Thank you!
