### PR TITLE
Fix leaky PDF text stroke

### LINKED ISSUE #3579: text `stroke` has an effect on the subsequent text
### Description

Once the stroke of the text is set, subsequent text will be affected. And even setting stroke to none cannot eliminate the effect.
```typst
#text("I can eat glass, it doesn't hurt me. 我能吞下玻璃而不伤身体。")

#text(stroke: 0.3pt, "I can eat glass, it doesn't hurt me. 我能吞下玻璃而不伤身体。")

#text(stroke: none, "I can eat glass, it doesn't hurt me. 我能吞下玻璃而不伤身体。")
```
图片

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Enter-tainer**
fix #3579

Please check! I'm not familiar with pdf

### CODE REVIEW

File: crates/typst-pdf/src/page.rs [hunk 1]
```diff
@@ -717,9 +717,12 @@ fn write_text(ctx: &mut PageContext, pos: Point, text: &TextItem) {
     let fill_transform = ctx.state.transforms(Size::zero(), pos);
     ctx.set_fill(&text.fill, true, fill_transform);
     if let Some(stroke) = &text.stroke {
-        ctx.set_stroke(stroke, true, fill_transform);
-        ctx.content
-            .set_text_rendering_mode(pdf_writer::types::TextRenderingMode::FillStroke);
+        if stroke.thickness.to_f32() > 0.0 {
```
Comment (Enter-tainer) [inline crates/typst-pdf/src/page.rs:720]: special handling for 0pt stroke. per https://github.com/typst/typst/issues/3579#issuecomment-1985285908 . I don't know if i'm doing right

File: crates/typst-pdf/src/page.rs [hunk 2]
```diff
@@ -765,6 +768,13 @@ fn write_text(ctx: &mut PageContext, pos: Point, text: &TextItem) {
     items.finish();
     positioned.finish();
     ctx.content.end_text();
+    if let Some(stroke) = &text.stroke {
+        if stroke.thickness.to_f32() > 0.0 {
+            ctx.set_stroke(stroke, false, fill_transform);
+            ctx.content
+                .set_text_rendering_mode(pdf_writer::types::TextRenderingMode::Fill);
+        }
+    }
```
Comment (Enter-tainer) [inline crates/typst-pdf/src/page.rs:777]: ideally we should reset the rendering state but i'm not sure if i'm doing right

**Comment by laurmaedje** [comment]
Thanks for the PR! I adjusted the logic a bit.
