### PR TITLE
Fix: ends-with

### LINKED ISSUE #1914: regex within ends-with function does not match as expected
### Description

This typst function is supposed to match a string ending in numbers 10-19.

```typst
#let ending-onex(eleven-number) = {
  if eleven-number.ends-with(regex("1[0-9]")) {
    show: eleven-number + " ends in the pattern 1[0-9]"
  }
  else {
    show:  eleven-number + " does not end in the pattern 1[0-9]"
  }
}
```

Here's what I get passing in different variations:

```typst
#ending-onex("typst13") // typst13 ends in the pattern 1[0-9]

#ending-onex("typst113") // typst113 does not end in the pattern 1[0-9]

#ending-onex("typst1113") // typst1113 ends in the pattern 1[0-9]

#ending-onex("typst213") // typst213 ends in the pattern 1[0-9]

#ending-onex("typst2113") // typst2113 does not end in the pattern 1[0-9]
```

All of these _should_ match. Is it a problem with my regex?

The line which defines regex matching in `ends-with` is here:

https://github.com/typst/typst/blob/2f81089995c87efdbce6c94bb29647cd1f213cfd/crates/typst/src/eval/str.rs#L118

I encountered this issue while writing the [nth package](https://github.com/typst/packages/pull/78) and used `contains(regex(".*1[0-9]")` as a workaround.

### Reproduction URL

https://typst.app/project/wZNPvqu7mWsM1JlOz_X8DK

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by NeillJohnston**
Closes #1914 

Just a small fix for the `ends-with` function not working with regex. As [Laurenz suspected](https://github.com/typst/typst/issues/1914#issuecomment-1685042804), `Regex::find_iter` [only reports non-overlapping matches](https://docs.rs/regex/1.9.4/regex/struct.Regex.html#method.find_iter). This PR fixes that by just adding an ending anchor to the regex (after putting it in parentheses so that alternations work as intended).

I'll note that it does feel a bit weird to directly modify a regex string, but this should be safe - as long as the original regex is valid, putting it in parentheses is valid, and then adding the anchor will be valid as well.

### CODE REVIEW

**Comment by laurmaedje** [comment]
This seems quite inefficient. I looked a bit and there seems to be no way to search from the back and also no built-in way to search for overlapping matches. However, [this comment](https://stackoverflow.com/questions/57497045/how-to-get-overlapping-regex-captures-in-rust#comment101464447_57497310) on StackOverflow was intriguing: 

> It's not possible to get the offset of the first match, then start the next search one codepoint in, repeating until no more matches?

Maybe we can do it like this?

File: crates/typst/src/eval/str.rs [hunk 1]
```diff
@@ -116,13 +116,22 @@ impl Str {
...
-                    .map_or(false, |m| m.end() == self.0.len())
+                let mut start_byte = 0;
+                while let Some(mat) = re.find_at(self, start_byte) {
+                    if mat.end() == self.0.len() {
+                        return true;
+                    }
+
+                    // There might still be a match overlapping this one, so
+                    // restart at the next code point
+                    if let Some(c) = &self[start_byte..].chars().next() {
```
Comment (laurmaedje) [inline crates/typst/src/eval/str.rs:127]: should `start_byte` be `mat.start()` here? otherwise, it doesn't really make sense to me.

Comment (NeillJohnston) [reply crates/typst/src/eval/str.rs:127]: Shit, thanks. Leftover from the previous commit.

**Comment by laurmaedje** [comment]
Thanks!
