### PR TITLE
Partially fix hide for line, polygon, table, grid

### LINKED ISSUE #2040: `hide` function does not work with lines and paths
### Description

```typst
#set page(height: auto, width: auto, margin: 0pt)
#set text(size: 2em)

#hide[
  This is some text

  #table(rows: 2, columns: 2)[a][b][c][d]
]

This is more text
```

This should hide all content before "this is more text", but here is the result:

image

Is this desired behavior?

### Reproduction URL

_No response_

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Enter-tainer**
somehow fix #2040

### CODE REVIEW

File: crates/typst/src/visualize/line.rs [hunk 1]
```diff
@@ -89,6 +89,7 @@ impl Layout for LineElem {
         let mut frame = Frame::soft(target);
         let shape = Geometry::Line(delta.to_point()).stroked(stroke);
         frame.push(start.to_point(), FrameItem::Shape(shape, self.span()));
+        frame.meta(styles, false);
```
Comment (Enter-tainer) [inline crates/typst/src/visualize/line.rs:92]: I dont really understant if I should pass true/false here. Please check

File: crates/typst/src/model/table.rs [hunk 2]
```diff
@@ -185,8 +185,11 @@ impl Layout for TableElem {
             styles,
             self.span(),
         );
-
-        Ok(layouter.layout(engine)?.fragment)
+        let mut frag = layouter.layout(engine)?.fragment;
+        for frame in &mut frag {
+            frame.meta(styles, false);
+        }
+        Ok(frag)
```
Comment (PgBiel) [inline crates/typst/src/model/table.rs:192]: Does this problem also affect grid, list and enum? (Please add tests for those!)

If so, this should probably be done inside `GridLayouter` itself, used by all 4 (table, grid, list, enum). Before doing that, though, please rebase first to avoid problems :p

If Laurenz is okay with this change, I can help here if needed.

File: tests/ref/layout/hide.png
Comment (Enter-tainer) [inline tests/ref/layout/hide.png:1]: Interestingly list markers are not correctly hidden. @PgBiel any idea on fix that?

Comment (PgBiel) [reply tests/ref/layout/hide.png:1]: This is tracked at https://github.com/typst/typst/issues/619

It's actually really hard to fix (you can see there was a PR where I attempted that). I'm not sure what's the best way to proceed.

Things have changed since then and there could be a way to solve this. For example, perhaps we could use some `list.item.marker` element or domething. It probably would deserve its own PR though.

Comment (Enter-tainer) [reply tests/ref/layout/hide.png:1]: ty for explaination. It is indeed harder than I originally expected. I decide no to fully solve the problem in this PR

**Comment by Enter-tainer** [comment]
How do you think of this idea? https://github.com/typst/typst/issues/2040#issuecomment-1879964962

> It is possible to make hide produce a GroupItem where hide: true then we can ignore this kind of group when export?

When I first see #2040 I was pretty surprised: wait? `display: none` can become wrong? But after playing with code I found that typst treat `hide` as a style item and all of hidden items are removed before export. This seems(or proves?) to be fragile. Is it ok to simply wrap hidden items with a `group` where `hide=true` then we ignore these group in export?

File: crates/typst/src/visualize/line.rs (hunk 1 above)
Comment (laurmaedje) [reply crates/typst/src/visualize/line.rs:92]: false is good

File: crates/typst/src/layout/grid/layout.rs [hunk 3]
```diff
@@ -376,6 +376,8 @@ impl<'a> GridLayouter<'a> {
 
         self.render_fills_strokes()?;
 
+        self.finished.iter_mut().for_each(|f| f.meta(self.styles, false));
```
Comment (laurmaedje) [inline crates/typst/src/layout/grid/layout.rs:379]: Could you use a for loop instead?

Comment (PgBiel) [reply crates/typst/src/layout/grid/layout.rs:379]: Maybe we could just move this to `finish_region`, right before pushing `output` to `self.finished`? (And maybe add a comment above it explaining the reasoning?)

Comment (laurmaedje) [reply crates/typst/src/layout/grid/layout.rs:379]: Sure

Comment (laurmaedje) [reply crates/typst/src/layout/grid/layout.rs]: good catch, then not

Comment (PgBiel) [reply crates/typst/src/layout/grid/layout.rs]: Thanks for verifying!

**Comment by laurmaedje** [comment]
Thanks!
