### PR TITLE
Fix hyphen duplication rule for some languages

### LINKED ISSUE #3235: Incorrect hyphenation in situations including dashes for some languages (e.g. polish)
### Description

In some languages—in polish[1], for example—while dividing a phrase consisted of words joined with a hyphen, it is required to split it on the hyphen, leaving it at the end of the line, but also to repeat it in the beginning of a new line. Typst doesn't do it. A minimal example is the following.

```typst
#set text(lang: "pl")
#set par(justify: true)

#{100 * [biało-czerwony ]}
```

Incorrect compilation results.

The correct hyphenation would be
```
biało-
-czerwony
```

---

I wasn't sure whether it should be a bug, or a feature report. I settled on a bug caused by the missing feature.

---

1: https://web.archive.org/web/20240120154340/https://www.ortograf.pl/zasady-pisowni/lacznik-zasady-pisowni

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by gabriel-araujjo**
This pr closes #3235.
Implement hyphen duplication rule for Czech, Croatian, Lower Sorbian, Polish, Portuguese, Slovak and Spanish.

So the input

```typst
#set page(width: 4cm, height: 4cm, margin: 2mm)
#set text(lang: "pt", region: "BR")
#set par(justify: true)

Alguma coisa no arco-da-velha é algo que está muito longe.

Um médico otorrinolaringologista cuida da garganta do paciente.
```

generates

right hyphen in portuguese

## Tasks

- [x] implementation
- [x] Tests
- [x] More complete rules on `should_repeat_hyphen()` function.

### CODE REVIEW

File: crates/typst/src/layout/inline/dash.rs [hunk 1]
```diff
@@ -0,0 +1,12 @@
+/// A dash at the end of a line.
+#[derive(Debug, Copy, Clone, Eq, PartialEq)]
+pub(super) enum Dash {
```
Comment (PgBiel) [inline crates/typst/src/layout/inline/dash.rs:3]: This should probably be moved to `inline/mod.rs`

File: crates/typst/src/layout/inline/mod.rs [hunk 2]
```diff
@@ -1446,3 +1478,50 @@ fn overhang(c: char) -> f64 {
...
+    // If there's a trimmed out space, we needn't repeat the hyphen. That's the case of a text like
+    // "... kebab é a -melhor- comida que existe", where the hyphens are a kind of emphasis marker.
+    if pred_line.trimmed.end != pred_line.end {
+        return false;
+    }
+
+    // The hyphen should repeat only in the languages that requires that feature.
+    // For more information see the discussion at https://github.com/typst/typst/issues/3235
+    if let Some(Item::Text(shape)) = pred_line.last.as_ref() {
+        match shape.lang.as_str() {
```
Comment (PgBiel) [inline crates/typst/src/layout/inline/mod.rs:1499]: Imho we should make this configurable within `TextElem`, something like `repeat-hyphenation-on-linebreak` (maybe a shorter name), which can be either `true`, `false` or `auto` (default, which varies depending on the language).

**Review by PgBiel — COMMENTED** [review]
Some initial observations:

File: crates/typst/src/layout/inline/mod.rs (hunk 2 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs:1499]: Indeed, a configuration within `TextElem` would make things more flexible. But the rules for hyphen duplication may have some tricky exceptions that are hard to express in configurable attributes --- for example: in Spanish we must not repeat the hyphen if the next word is capitalized.

Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs:1499]: I don't know if there's other exceptions like that in other languages grammars.

Comment (PgBiel) [reply crates/typst/src/layout/inline/mod.rs:1499]: I think the option shouldn't be that flexible in principle. `true` would correspond to always doing it, while for `auto` we can accurately map the language to the correct behavior.

That way, you can manually change it to `false` for some sections of text as needed, which should allow for a good degree of customization already.

Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs:1499]: > ... something like repeat-hyphenation-on-linebreak (maybe a shorter name)

What about `linebreak-hyphen`?

The possible values would be
- `"single"`: a single hyphen is placed at the end of the line
- `"repeat"`: the hyphen is also repeated at the beginning of the next line
- `auto` (default): the language rules are accurately mapped to the correct behavior.

Comment (PgBiel) [reply crates/typst/src/layout/inline/mod.rs:1499]: Seems ok to me as well.

Comment (PgBiel) [reply crates/typst/src/layout/inline/mod.rs:1499]: With that said, it could be a good idea to hold off implementing that parameter before further input from the maintainers. (cc @laurmaedje)

File: crates/typst/src/layout/inline/shaping.rs [hunk 3]
```diff
@@ -492,6 +492,56 @@ impl<'a> ShapedText<'a> {
         });
     }
 
+    /// Prepend a hyphen to begin of the text.
+    pub fn prepend_hyphen(&mut self, engine: &Engine, fallback: bool) {
```
[the remark this answers is not in the document]
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/shaping.rs]: I have join both functions logic in`insert_hyphen()` function.

File: crates/typst/src/layout/inline/mod.rs [hunk 4]
```diff
@@ -1446,3 +1478,50 @@ fn overhang(c: char) -> f64 {
...
+            //
+            // Croatian: see http://pravopis.hr/pravilo/spojnica/68/
+            //
+            // Polish: see https://www.ortograf.pl/zasady-pisowni/lacznik-zasady-pisowni
+            //
+            // Portuguese: see Base XX of "Acordo Ortográfico da Língua Portuguesa de 1990"
+            // https://www2.senado.leg.br/bdsf/bitstream/handle/id/508145/000997415.pdf
+            //
+            // Slovak: see https://www.zones.sk/studentske-prace/gramatika/10620-pravopis-rozdelovanie-slov/
+            "dsb" | "cs" | "hr" | "pl" | "pt" | "sk" => true,
```
[the remark this answers is not in the document]
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: Croatian, Lower Sorbian and Slovak were missing in Lang constants. So I have added them at 5e23d80485375756e8e12ce91c15200693f5c607.

File: crates/typst/src/layout/inline/mod.rs (hunk 2 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: In Spanish and Portuguese, at least[^1], the hyphenation is an orthographic rule. So if you do not obey it, you are making a orthographic mistake, such as misspelling a word. If we do not allow to config that feature, those mistakes will be avoided. 

On the other hand, we don't implement the hyphenation exhaustively, maybe in other languages the hyphen duplication is more a matter of style.

[^1]: The fonts I got this are the RAE orthographic guide and the 1990 Portuguese Orthographic Agreement (the current one). I can read in that two languages. For the other languages I am trusting on automatic translation of the fonts.

File: crates/typst/src/layout/inline/mod.rs [hunk 5]
```diff
@@ -1079,13 +1106,21 @@ fn line<'a>(
...
+        {
             if hyphen || start < range.end || before.is_empty() {
                 let mut reshaped = shaped.reshape(engine, &p.spans, start..range.end);
                 if hyphen || shy {
                     reshaped.push_hyphen(engine, p.fallback);
                 }
 
+                if prepend_hyphen && before.is_empty() {
+                    reshaped.prepend_hyphen(engine, p.fallback);
+                }
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:1122]: I'm not too fond of the duplication in doing it potentially in this branch (for the last item) and then again in the later branch (for the first item, if first != last). Maybe we could just do it at the end, similarly to `maybe_adjust_first_glyph`?

File: crates/typst/src/layout/inline/mod.rs [hunk 6]
```diff
@@ -1446,3 +1489,56 @@ fn overhang(c: char) -> f64 {
...
+
+    // If there's a trimmed out space, we needn't repeat the hyphen. That's the case of a text like
+    // "... kebab é a -melhor- comida que existe", where the hyphens are a kind of emphasis marker.
+    if pred_line.trimmed.end != pred_line.end {
+        return false;
+    }
+
+    // The hyphen should repeat only in the languages that requires that feature.
+    // For more information see the discussion at https://github.com/typst/typst/issues/3235
+    if let Some(Item::Text(shape)) = pred_line.last.as_ref() {
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:1509]: WE could get rid of the indent here with `let .. else ..`.

File: crates/typst/src/layout/inline/mod.rs [hunk 7]
```diff
@@ -1446,3 +1489,56 @@ fn overhang(c: char) -> f64 {
...
+
+/// Whether the hyphen should repeat at the start of the next line.
+fn should_repeat_hyphen(pred_line: &Line) -> bool {
+    // If the predecessor line does not end with a Dash::HardHyphen, we shall not place a hyphen at
+    // the start of the next line.
+    if pred_line.dash != Some(Dash::HardHyphen) {
+        return false;
+    }
+
+    // If there's a trimmed out space, we needn't repeat the hyphen. That's the case of a text like
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:1501]: could you wrap these comments at 80 columns?

File: crates/typst/src/layout/inline/mod.rs [hunk 8]
```diff
@@ -1446,3 +1489,56 @@ fn overhang(c: char) -> f64 {
...
+            // Czech: see https://prirucka.ujc.cas.cz/?id=164
+            //
+            // Croatian: see http://pravopis.hr/pravilo/spojnica/68/
+            //
+            // Polish: see https://www.ortograf.pl/zasady-pisowni/lacznik-zasady-pisowni
+            //
+            // Portuguese: see Base XX of "Acordo Ortográfico da Língua Portuguesa de 1990"
+            // https://www2.senado.leg.br/bdsf/bitstream/handle/id/508145/000997415.pdf
+            //
+            // Slovak: see https://www.zones.sk/studentske-prace/gramatika/10620-pravopis-rozdelovanie-slov/
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:1522]:
```suggestion
            // - Lower Sorbian: see https://dolnoserbski.de/ortografija/psawidla/K3
            // - Czech: see https://prirucka.ujc.cas.cz/?id=164
            // - Croatian: see http://pravopis.hr/pravilo/spojnica/68/
            // - Polish: see https://www.ortograf.pl/zasady-pisowni/lacznik-zasady-pisowni
            // - Portuguese: see https://www2.senado.leg.br/bdsf/bitstream/handle/id/508145/000997415.pdf (Base XX)
            // - Slovak: see https://www.zones.sk/studentske-prace/gramatika/10620-pravopis-rozdelovanie-slov/
```
(the URLs can of course exceed 80 columns)

File: crates/typst/src/layout/inline/mod.rs (hunk 2 above)
Comment (laurmaedje) [reply crates/typst/src/layout/inline/mod.rs]: Let's leave it non-configurable then. When other languages come up, we can add support for them as well.

File: crates/typst/src/layout/inline/mod.rs [hunk 9]
```diff
@@ -298,6 +298,19 @@ impl SpanMapper {
...
+#[derive(Debug, Copy, Clone, Eq, PartialEq)]
+pub(super) enum Dash {
+    /// A hyphen added to break a word
+    SoftHyphen,
+    /// Regular hyphen, present on a compound word. Ex.: beija-flor
+    HardHyphen,
+    /// An em dash
+    Long,
+    /// An en dash
+    Short,
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/mod.rs:311]:
```suggestion
    /// A hyphen added to break a word.
    SoftHyphen,
    /// Regular hyphen, present in a compound word, e.g. beija-flor.
    HardHyphen,
    /// An em dash.
    Long,
    /// An en dash.
    Short,
```

File: crates/typst/src/layout/inline/mod.rs (hunk 2 above)
Comment (PgBiel) [reply crates/typst/src/layout/inline/mod.rs]: As I see it, the main problem is that using `#set text(lang: ...)` comes with several features which one might or might not want. Most of them can be overridden - e.g. supplements. I don't see why that wouldn't be the case here either - one might want to set the lang for reasons other than this, and/or configure hyphenation despite their `lang` setting.

I'd say being able to at least toggle between always repeating hyphenation and never doing so would be nice, in order to allow users to have maximum control over their documents. There might be differing requirements depending not only on the language but also on the region, or the target journal for example.

With that said, that's not something that is strictly necessary for this PR - it could be implemented separately, and could have further discussion first if needed; just sharing my 2 cents.

Comment (laurmaedje) [reply crates/typst/src/layout/inline/mod.rs]: I'm a bit concerned about the proliferation of very specific options, especially on the `text` function which already has a lot of options. Every extra knob incurs some UX complexity (even if users can mostly ignore it). 

I see how this one is perhaps a gray area, but generally the shaping pipeline might do all sorts of language-specific things which are just automatic and this feels similar.

The user perspective aside, I'm also a bit concerned about this from an implementation perspective. A single property obviously doesn't make a difference, but doing tons of style chain lookups for every single paragraph can also get expensive (especially if they end up happening more than once per paragraph; that's why many properties are cached in the `Preparation` struct).

Comment (PgBiel) [reply crates/typst/src/layout/inline/mod.rs]: I see what you mean.

While I see the value of having this option, I can also see how it's not really needed at this moment, and I think you have a good argument. In this case, we should likely wait until someone requests this feature to have a better idea of potential use cases and design the API around them, if needed.

File: crates/typst/src/layout/inline/mod.rs (hunk 6 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: Nice hint! The code if cleaner that way!

File: crates/typst/src/layout/inline/mod.rs (hunk 7 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: Sure. Done at last commit.

File: crates/typst/src/layout/inline/mod.rs (hunk 8 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: Done!

File: crates/typst/src/layout/inline/mod.rs (hunk 9 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: Done!

File: crates/typst/src/layout/inline/mod.rs (hunk 5 above)
Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: I have created a `do_prepend_hyphen` variable. So I can reuse it on both places.

Comment (laurmaedje) [reply crates/typst/src/layout/inline/mod.rs]: What I meant was more to have the `prepend_hyphen` itself just a single time right before `if maybe_adjust_first_glyph {` with a construction similar to the `first.as_mut().or(last.as_mut())` used there. Do you think that'd be possible and make sense?

Comment (gabriel-araujjo) [reply crates/typst/src/layout/inline/mod.rs]: I think I got it now.

**Comment by laurmaedje** [comment]
Thank you!
