### PR TITLE
Let the lexer respect linebreaks within inline raw

### LINKED ISSUE #3738: Syntax highlighting wrong with single backtick
### Description

When code blocks with a single back tick have syntax highlighting applied, the results can sometimes be weird, this was especially noticeable with comments/

``````typ
#set raw(lang:"python")

// good
```
# comment
for i in range(10):
  print(i)```

// bad
`# comment
for i in range(10):
  print(i)`
``````

image

### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by Leedehai**
Fixes #3738.

### CODE REVIEW

**Comment by Leedehai** [comment]
The tests are broken due to an unrelated issue. PR #3754 can fix them.

File: crates/typst-syntax/src/lexer.rs [hunk 1]
```diff
@@ -353,6 +350,19 @@ impl Lexer<'_> {
...
 
+    fn inline_raw(&mut self, start: usize, end: usize, backticks: usize) {
+        self.s.jump(start + backticks);
+        let inner = self.s.to(end - backticks);
+        for line in split_newlines(inner).into_iter() {
+            self.s.eat_newline();
+            self.push_raw(SyntaxKind::RawTrimmed);
+            self.s.advance(line.len());
+            self.push_raw(SyntaxKind::Text);
+        }
```
Comment (laurmaedje) [inline crates/typst-syntax/src/lexer.rs:361]: I think lexing directly with the scanner rather than relying on `split_newlines` would be pretty simple and more efficient here.

File: crates/typst-syntax/src/lexer.rs [hunk 2]
```diff
@@ -353,6 +350,26 @@ impl Lexer<'_> {
         self.s.jump(end);
     }
 
+    fn inline_raw(&mut self, start: usize, end: usize, backticks: usize) {
+        self.s.jump(start + backticks);
+
+        while self.s.cursor() < end - backticks {
+            let c = self.s.peek().unwrap(); // Valid, as we are not at end of file.
+            if is_newline(c) {
```
Comment (laurmaedje) [inline crates/typst-syntax/src/lexer.rs:358]:
```suggestion
            if self.s.at(is_newline) {
```

**Comment by laurmaedje** [comment]
Thanks!
