### PR TITLE
fix a parser bug causing `x.)` to be treated as a field access

### LINKED ISSUE #2044: Math: Dot parsing depends on space being after it.
### Description

This dot is parsed as text `$step(phi.alt. )$`
This one is parsed as a field access dot: `$step(phi.alt.)$`

Bug? encountered while trying to fix my formatter .

I think both should be parsed as field access and if you wan't text, you write `phi.alt .` instead.

I would be interested to fix it.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by dyc3**
fixes #2044

### CODE REVIEW

File: crates/typst-syntax/src/parser.rs [hunk 1]
```diff
@@ -1786,3 +1791,41 @@ impl<'s> Parser<'s> {
         self.nodes.drain(start..end);
     }
 }
+
```
Comment (Dherse) [inline crates/typst-syntax/src/parser.rs:1794]: Can you please either uncomment this code or fix the tests? :)

Comment (laurmaedje) [reply crates/typst-syntax/src/parser.rs:1794]: This code should probably deleted since we don't use unit tests for the parser.

**Comment by laurmaedje** [comment]
Thanks!
