### PR TITLE
Wrap outline entry body in LRE/RLE + make smart quotes ignore directional control characters

### LINKED ISSUE #4476: RTL headings with LTR ending rendered incorrectly in Outline
### Description

Hi!

The following code reproduces the issue I'm encountering:

```typst
#set text(lang: "he")

#outline()

= הוקוס Pocus
```

which is rendered using the latest Typst version as:

outline-rendering-incorrectly

i.e. the "Pocus", which is part of the heading, "switches places" with the page number.

A workaround (which probably doesn't fix all cases) for now is adding:
```typst
#show outline.entry: it => {
  box(it.body)

  box(width: 1fr, it.fill)

  it.page
}
```

(The workaround is known to break when an outline entry needs multiple lines, see #4477).

in which case we get the desired result:

outline-rendering-correctly

### Reproduction URL

_No response_

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by bluebear94**
Fixes #4476.

### CODE REVIEW

File: crates/typst/src/model/outline.rs [hunk 1]
```diff
@@ -500,7 +500,18 @@ impl Show for Packed<OutlineEntry> {
...
+                match TextElem::dir_in(styles) {
+                    crate::layout::Dir::RTL => "\u{202B}",
+                    _ => "\u{202A}",
+                }
+                .into(),
+            )
+            .pack(),
+        );
         seq.push(self.body().clone().linked(Destination::Location(location)));
+        seq.push(TextElem::new("\u{202C}".into()).pack());
```
Comment (laurmaedje) [inline crates/typst/src/model/outline.rs:514]: I think this kind of isolation could be moved into a helper function, e.g. `crate::text::isolate`.

Comment (laurmaedje) [reply crates/typst/src/model/outline.rs:514]: I also wonder whether we want LRE or LRI. Difference:

```typ
#set text(lang: "he")
#let val = "זוהי כותרת ארוכה מאוד שתורגמה על ידי תוכנת מחשב ועל כן עשויה להיות שגיאות דקדוקיות"
\u{202B} #val Pocus \u{202C} #box(width: 1fr, repeat[.]) 1 \
\u{2066} #val Pocus \u{2069} #box(width: 1fr, repeat[.]) 1
```

See also: https://github.com/typst/typst/issues/3696#issuecomment-2115547827

File: crates/typst/src/layout/inline/collect.rs [hunk 2]
```diff
@@ -201,7 +202,7 @@ pub fn collect<'a>(
                 );
                 let peeked = iter.peek().and_then(|(child, _)| {
                     if let Some(elem) = child.to_packed::<TextElem>() {
-                        elem.text().chars().next()
+                        elem.text().chars().find(|c| !is_directional_control(*c))
```
Comment (laurmaedje) [inline crates/typst/src/layout/inline/collect.rs:205]: could you explain when you use `is_directional_control` over `is_ignorable` / `is_exterior_to_quote`? I don't quite understand the difference.

Comment (bluebear94) [reply crates/typst/src/layout/inline/collect.rs:205]: `is_directional_control` returns true for characters that have no effect on the smart quote algorithm – it’s as if they aren’t there in the first place. This is different from `is_ignorable`, which determines which characters lie immediately outside a quote, hence the renaming.

Comment (laurmaedje) [reply crates/typst/src/layout/inline/collect.rs:205]: Sounds like `is_ignorable` would be a good name for what `is_directional_control` is doing. I wonder whether we can apply the `Default_Ignorable` Unicode property to filter out more stuff. This is already used in paragraph layout.

File: crates/typst/src/text/smartquote.rs [hunk 3]
```diff
@@ -168,10 +168,14 @@ impl Default for SmartQuoter {
     }
 }
 
-fn is_ignorable(c: char) -> bool {
+fn is_exterior_to_quote(c: char) -> bool {
     c.is_whitespace() || is_newline(c)
 }
 
+pub(crate) fn is_ignorable(c: char) -> bool {
+    icu_properties::sets::default_ignorable_code_point().contains(c)
```
Comment (laurmaedje) [inline crates/typst/src/text/smartquote.rs:176]: currently, we don't use the compiled_data from icu4x, but rather generated one (see [here for how it works](https://github.com/typst/typst/blob/59374f737079472aa5694b69ebced8c4cd5f9dfc/crates/typst/src/layout/inline/linebreak.rs#L55-L59)) and [here for the reason](https://github.com/typst/typst/pull/4485#issuecomment-2211732974). This might change in the future. Either we investigate whether we should change that before merging this PR or it should switch to the blob data.

File: crates/typst/src/model/outline.rs (hunk 1 above)
Comment (laurmaedje) [reply crates/typst/src/model/outline.rs]: So, this leaves this as the only remaining question before merge.

File: crates/typst/src/text/smartquote.rs (hunk 3 above)
Comment (bluebear94) [reply crates/typst/src/text/smartquote.rs]: Changed to use the generated `DEFAULT_IGNORABLE_DATA`.

File: crates/typst/src/model/outline.rs (hunk 1 above)
Comment (bluebear94) [reply crates/typst/src/model/outline.rs]: > ```typst
> #set text(lang: "he")
> #let val = "זוהי כותרת ארוכה מאוד שתורגמה על ידי תוכנת מחשב ועל כן עשויה להיות שגיאות דקדוקיות"
> \u{202B} #val Pocus \u{202C} #box(width: 1fr, repeat[.]) 1 \
> \u{2066} #val Pocus \u{2069} #box(width: 1fr, repeat[.]) 1
> ```

I think you mean `\u{2067}` (assuming you meant to put RLI instead of LRI). With that change, the two lines look identical.

Comment (laurmaedje) [reply crates/typst/src/model/outline.rs]: My bad. But the lines being the same in this case doesn't mean it's always the same, so the question remains.

**Comment by laurmaedje** [comment]
Thanks!

**Comment by istudyatuni** [comment]
Strange, #4476 doesn't exist
