### PR TITLE
Synthesize `block` and `quotes` & improve documentation for `quote`

### LINKED ISSUE #2541: Example for `quote` `attribution` argument does not work
### Description

Specifically, this part of the example:
```typ
#show quote.where(block: false): it => [
  "#it.body"
  #if it.attribution != none [(#it.attribution)]
]
#quote(attribution: link("https://typst.app/home")[typst.com])[
  Compose papers faster
]
```

The show rule is never applied in the first place:
```typ
#show quote.where(block: false): it => [Modified quote]
#quote[Original quote]
```
renders as
“Original quote”

Removing `.where(block: false)` works properly:
```typ
#show quote: it => [Modified quote]
#quote[Original quote]
```
Modified quote

May relate to #2530

### Reproduction URL

https://typst.app/docs/reference/text/quote/#parameters-attribution

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by tingerrr**
This PR adds a `Synthesize` impl for `QuoteElem`, such that similar to raw, a selector can be used on the fields `block` and `quotes`. It also improves the documentation, streamlining some of the examples as well as removing the note about CSL coming soon (:tada:).

Resolves #2541.

### CODE REVIEW

File: crates/typst-library/src/text/quote.rs [hunk 1]
```diff
@@ -33,15 +33,19 @@ use crate::prelude::*;
...
-    /// #set quote(block: true)
-    /// #quote(attribution: [JFK])[Ich bin ein Berliner.]
+    /// #let descartes = quote(attribution: [René Descartes])[
+    ///   cogito, ergo sum
+    /// ]
+    /// #let jfk = quote(block: true, attribution: [JFK])[
+    ///   Ich bin ein Berliner.
+    /// ]
+    /// An inline citation would look like this: #descartes, and a block
+    /// equation like this: #jfk
```
Comment (laurmaedje) [inline crates/typst-library/src/text/quote.rs:48]: Why store the quotes in variables? I think this adds unnecessary complexity.

File: crates/typst-library/src/text/quote.rs [hunk 2]
```diff
@@ -59,11 +63,12 @@ pub struct QuoteElem {
...
     /// ```example
     /// #set text(lang: "de")
+    /// Ein deutsch-sprechender Author zitiert unter umständen JFK:
     /// #quote[Ich bin ein Berliner.]
     ///
     /// #set text(lang: "en")
-    /// #set quote(quotes: true)
-    /// #quote(block: true)[I am a Berliner.]
+    /// And an english speaking one may translate the quote:
+    /// #quote[I am a Berliner.]
```
Comment (laurmaedje) [inline crates/typst-library/src/text/quote.rs:71]: could you wrap these at 37 cols so that they fit side-by-side in the docs?

File: crates/typst-library/src/text/quote.rs [hunk 3]
```diff
@@ -74,10 +79,10 @@ pub struct QuoteElem {
...
     /// #quote(attribution: [René Descartes])[cogito, ergo sum] \
     ///
-    /// #show quote.where(block: false): it => [
-    ///   "#it.body"
-    ///   #if it.attribution != none [(#it.attribution)]
-    /// ]
+    /// #show quote.where(block: false): it => {
+    ///   ["] + h(0pt, weak: true) + it.body + h(0pt, weak: true) + ["]
+    ///   if it.attribution != none [ (#it.attribution)]
+    /// }
```
Comment (laurmaedje) [inline crates/typst-library/src/text/quote.rs:85]: Please add blank lines between show rules and following content (and generally between "blocks" of markup). I think there are some other instances of this.

File: crates/typst-library/src/text/quote.rs [hunk 4]
```diff
@@ -3,7 +3,7 @@ use crate::layout::{BlockElem, HElem, PadElem, Spacing, VElem};
 use crate::meta::{CitationForm, CiteElem};
 use crate::prelude::*;
 
-/// Displays a quote alongside it's author.
+/// Displays a quote alongside an attribution.
```
Comment (laurmaedje) [inline crates/typst-library/src/text/quote.rs:6]:
```suggestion
/// Displays a quote alongside an optional attribution.
```

File: crates/typst-library/src/text/quote.rs (hunk 1 above)
Comment (tingerrr) [reply crates/typst-library/src/text/quote.rs:48]: The 80 column word wrap always made the examples hard to read, imo.

File: crates/typst-library/src/text/quote.rs (hunk 2 above)
Comment (tingerrr) [reply crates/typst-library/src/text/quote.rs:71]: Should this generally be the case in doc comments? And is this the total or starting from the comment token?

File: crates/typst-library/src/text/quote.rs (hunk 1 above)
Comment (laurmaedje) [reply crates/typst-library/src/text/quote.rs:48]: 80 columns? The examples are typically wrapped at ~37 cols to end up side-by-side.

File: crates/typst-library/src/text/quote.rs (hunk 2 above)
Comment (laurmaedje) [reply crates/typst-library/src/text/quote.rs:71]: Starting after `/// ` . Not generally for doc comments, only for Typst code examples with the `preview` tag. It's not a hard and fast rule (sometimes, it reduces legibility), but I at least always try whether there's a good way to fit the example into 37 cols because it just looks better side-by-side in the docs.

Comment (tingerrr) [reply crates/typst-library/src/text/quote.rs]: Well, I tried, the examples are a bit hard to put into 37 cols without making them unnecessarily long in height, so I went for a "best effort" approach. The examples in question are all `example` and not `preview`, so it should be fine. They should definitely look better than they did before.

Comment (laurmaedje) [reply crates/typst-library/src/text/quote.rs]: Sorry, I meant `example`, not `preview`.

**Comment by laurmaedje** [comment]
Thanks!
