### PR TITLE
Fix: `number-align` should align line/number baselines

### LINKED ISSUE #4014: Align equation number vertically to the formula baseline - `number-align` in `math.equation`
### Description

When a single-line math formula is presented, I would like to have the equation number aligned with the correct baseline. Now, if you include for example a sum, the height of the block is adjusted and the equation number is aligned with respect to the total height. This is not the case in LaTex, for example. Compare the first (LaTex) and second (Typst) snippets along with a rendered images.

```
\begin{equation}
    c_{t+1}(v) = c_{t}(v) - deg(v) \cdot  \mathbb{1}(c_{t}(v) - deg(v)) + \sum_{u \in N(v)} \mathbb{1}(c_{t}(u) - deg(u)) \quad \forall v \in V
\end{equation}
```
image

```
#set math.equation(numbering: "(1)", number-align: end + horizon)

$ c_(t+1)(v) = c_(t)(v) - deg(v) dot.c bb(1)(c_(t)(v) - deg(v)) + sum_(u in.small N(v)) bb(1)(c_(t)(u) - deg(u)) wide forall v in V $
```
image

### Use Case

----

### PR DESCRIPTION
**Pull request by Leedehai**
Fixes #4014.

The number should be put at the vertical center only if the alignment is `FixedAlignment::Center` and there are multiple lines. Otherwise, the number's baseline should be on the baseline of the math line it is supposed to be aligned with.

### CODE REVIEW

File: crates/typst/src/math/row.rs [hunk 1]
```diff
@@ -375,16 +375,16 @@ impl Iterator for LeftRightAlternator {
 pub struct MathRunFrameBuilder {
     /// The size of the resulting frame.
     pub size: Size,
-    /// Sub frames for each row, and the positions where they should be pushed into
-    /// the resulting frame.
-    pub frames: Vec<(Frame, Point)>,
+    /// Each row: the baseline, the frame, and the positions where they should
+    /// be pushed into the resulting frame.
+    pub frames: Vec<(Abs, Frame, Point)>,
```
Comment (EpicEricEE) [inline crates/typst/src/math/row.rs:380]: I don't think this is necessary as the baseline can already be extracted from the frame

**Comment by laurmaedje** [comment]
Thanks!
