### PR TITLE
Fix `typst watch` not working with some text editors

### LINKED ISSUE #1651: `typst watch` doesn't work when editing the watched file with (neo)vim
### Description

The watch command does not seem to work with (neo)vim anymore.

The issue seems to come from the fact that when saving a file, vim will rename the old file and write a new file with the old name. However, for notify-rs this causes a `Remove` event to be triggered on that file, and removed files are implicitly unwatched on some platforms according to their docs:

> On some platforms, if the path is renamed or removed while being watched, behaviour may be unexpected. See discussions in [#165](https://github.com/notify-rs/notify/issues/165) and [#166](https://github.com/notify-rs/notify/issues/166). If less surprising behaviour is wanted one may non-recursively watch the parent directory as well and manage related events.

When running the code through gdb, after saving a first time, the program just waits for events [there](https://github.com/typst/typst/blob/19345f76576623951d61b83dc3435628a0b48f65/crates/typst-cli/src/watch.rs#L38), and saving the file again does not trigger events.

**Note**: the oldest commit where this saving behavior caused an issue was e1d76960eb67443fbe58e5af0cc6da2facee26a1, trying to unwatch the dependencies, some of which were already unwatched, caused a `failed to unwatch something.typ` error to happen.

## steps to reproduce

- create a typst file, let's say `test.typ`
- watch the file with `typst watch test.typ`
- edit the file in vim or neovim
- save the file (with `:w`), this one should work
- try saving again, and the modifications are not picked up by typst

Vim's saving method can be changed to copy the new file into the old file by executing the command `:set backupcopy=yes`, in this case the `typst watch` command works as expected.

### Reproduction URL

_No response_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by tretre91**
This fixes #1651.

As stated in the issue, the modified code unwatches all files for which we received a `Remove` event, and allows these files to be watched again if they still exist and the compilation still depends on them.

Note that I was only able to test this on Linux, I'm unsure whether this fix could create issues on other platforms.

### CODE REVIEW

File: crates/typst-cli/src/watch.rs [hunk 1]
```diff
@@ -34,20 +34,41 @@ pub fn watch(mut command: CompileCommand) -> StrResult<()> {
     let timeout = std::time::Duration::from_millis(100);
     let output = command.output();
     loop {
+        let mut removed = HashSet::new();
```
Comment (istudyatuni) [inline crates/typst-cli/src/watch.rs:37]: Maybe leave a note why this is needed?

**Comment by tretre91** [comment]
Should I also include the corresponding issue's id or a link to the issue in the note ?

**Comment by istudyatuni** [comment]
I think this comment is descriptive enough

File: crates/typst-cli/src/watch.rs [hunk 2]
```diff
@@ -34,20 +34,45 @@ pub fn watch(mut command: CompileCommand) -> StrResult<()> {
...
+                let path = &event.paths[0];
+                removed.insert(path.clone());
+
+                // Remove the watch if it still exists.
+                if let Err(notify::Error { kind, .. }) = watcher.unwatch(path) {
+                    match kind {
+                        notify::ErrorKind::WatchNotFound => {}
+                        _ => return Err("failed to unwatch file".into()),
+                    }
+                }
```
Comment (laurmaedje) [inline crates/typst-cli/src/watch.rs:63]: Do we really want this to return for `kind != notify::ErrorKind::WatchNotFound`? In the `watch_dependencies` function below I just did `watcher.unwatch(&path).ok()` to ignore the result. After all, the unwatching is only an optimization basically.

**Comment by laurmaedje** [comment]
Thank you!
