### PR TITLE
Ensure lorem produces exact word count by skipping hyphens

### LINKED ISSUE #6186: #lorem has a glitch at the 194th word
### Description

When experimenting with word counting (using `typst-wordometer`), I noticed that `#lorem` produces an empty word with a dot at position 194 (counting from 1), and a hyphen wenn generating at least 195 words on that position. Word counting will usually not count the hypen and neither the empty sentence, so word counters's result differs from the number of words supplied to `#lorem`.

Steps to reproduce:
```typst
#lorem(193)

#lorem(194)

#lorem(195)
```

I believe this to happen again at any position where a hyphen is in the text.

Expected behavior: In my opinion, hyphens should not count as "words", or the documentation should make it clear that `#lorem` can not actually be trusted to produce the exact number of words specified.

Suggested fix: Return hypens additionally, without counting them as words.

### Reproduction URL

https://typst.app/project/rspchq7jyWPp2u0Ffhy6jx

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

### PR DESCRIPTION
**Pull request by 3w36zj6**
close #6186

This issue was initially marked as an upstream problem, but the author of lipsum suggested using `MarkovChain::iter`. 
Therefore, this PR adds a custom implementation to Typst that takes the word count into account.

```typ
#import "@preview/wordometer:0.1.4": word-count

#word-count(total => [
  #lorem(193) \
  #[`#lorem(193)`: *#total.words words*] <no-wc>
], exclude: <no-wc>)

#word-count(total => [
  #lorem(194) \
  #[`#lorem(194)`: *#total.words words*] <no-wc>
], exclude: <no-wc>)

#word-count(total => [
  #lorem(195) \
  #[`#lorem(195)`: *#total.words words*] <no-wc>
], exclude: <no-wc>)
```

image

### CODE REVIEW

File: crates/typst-library/src/text/lorem.rs [hunk 1]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+}
+
+// https://docs.rs/lipsum/0.9.1/src/lipsum/lib.rs.html#403-413
+thread_local! {
+    static LOREM_CHAIN: RefCell<MarkovChain<'static>> = RefCell::new({
+        let mut chain = MarkovChain::new();
+        chain.learn(LOREM_IPSUM);
+        chain.learn(LIBER_PRIMUS);
+        chain
+    });
```
Comment (istudyatuni) [inline crates/typst-library/src/text/lorem.rs]: If I understand correctly, this code will run on each invocation of typst-cli/downstream tools? Maybe it's better to use `OnceCell` to defer initialization to first use of `generate_lorem`?

Comment (saecki) [reply crates/typst-library/src/text/lorem.rs]: No, this code will be lazily run once on every thread. Though depending on how the rayon manages its thread-pool this may still be a waste of resources. Instead this should use a `LazyLock` like most other parts of the Typst code base.

File: crates/typst-library/src/text/lorem.rs [hunk 2]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+                sentence.push('\u{2013}');
+                first = false;
+                continue;
+            }
+
+            word_count += 1;
+
+            if first {
+                sentence.push_str(&capitalize(word));
+                needs_cap = sentence.ends_with(punctuation);
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: This check can be pulled out of the if statement, since it's present in both branches. I'd just put it at the end of the loop.

File: crates/typst-library/src/text/lorem.rs [hunk 3]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+        let mut needs_cap = false;
+        let mut first = true;
+
+        while word_count < n {
+            let Some(word) = iter.next() else { break };
+
+            // Skip `--` without counting it as a word; append an en-dash
+            // to the output instead.
+            if word == "--" {
+                if !first {
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: This check can be lifted out of the if statement as the first thing right after getting the next word. Since the first word will always be `Lorem`, we can remove the `first` variable and use `word_count == 0`/`word_count > 0` instead.

File: crates/typst-library/src/text/lorem.rs [hunk 4]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+                    sentence.push(' ');
+                }
+                sentence.push('\u{2013}');
+                first = false;
+                continue;
+            }
+
+            word_count += 1;
+
+            if first {
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: Since `"Lorem"` is already captialized, we can remove this branch of the if statement.

File: crates/typst-library/src/text/lorem.rs [hunk 5]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+                sentence.push_str(&capitalize(word));
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: Now that this is the only occurence of `capitalize`, I would just inline it and push directly into the `sentence` string, instead of creating an intermediate `String` buffer.

File: crates/typst-library/src/text/lorem.rs [hunk 6]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+        return String::new();
+    }
+
+    // https://docs.rs/lipsum/0.9.1/src/lipsum/lib.rs.html#344-382
+    LOREM_CHAIN.with(|chain| {
+        let chain = chain.borrow();
+        let mut iter = chain.iter_from(("Lorem", "ipsum"));
+
+        // Punctuation characters which end a sentence.
+        let punctuation: &[char] = &['.', '!', '?'];
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: For readability I would make this a constant, and while we're at it I'd convert it to an array : `[char; 3]` instead.

File: crates/typst-library/src/text/lorem.rs [hunk 7]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
...
+            if word == "--" {
+                if !first {
+                    sentence.push(' ');
+                }
+                sentence.push('\u{2013}');
+                first = false;
+                continue;
+            }
+
+            word_count += 1;
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: Finally I'd also move this to the end of the loop

File: crates/typst-library/src/text/lorem.rs [hunk 8]
```diff
@@ -20,5 +24,96 @@ pub fn lorem(
     /// The length of the blind text in words.
     words: usize,
 ) -> Str {
-    lipsum::lipsum(words).replace("--", "–").into()
+    generate_lorem(words).into()
+}
+
+// https://docs.rs/lipsum/0.9.1/src/lipsum/lib.rs.html#403-413
+thread_local! {
+    static LOREM_CHAIN: RefCell<MarkovChain<'static>> = RefCell::new({
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: To make attributing everything easier, could you move this static into the `generate_lorem` function, and then add a copyright notice like this in the code: https://github.com/typst/typst/blob/c817e592b735ef77af5eed079d411369cf433362/crates/typst-utils/src/scalar.rs#L46
And add an entry here: https://github.com/typst/typst/blob/c817e592b735ef77af5eed079d411369cf433362/NOTICE#L22

File: crates/typst-library/src/text/lorem.rs [hunk 9]
```diff
@@ -61,59 +42,64 @@ fn generate_lorem(n: usize) -> String {
...
 
-            if first {
-                sentence.push_str(&capitalize(word));
-                needs_cap = sentence.ends_with(punctuation);
-                first = false;
-            } else {
+        // Skip `--` without counting it as a word; append an en-dash
+        // to the output instead.
+        if word == "--" {
+            if word_count > 0 {
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: Could you move this check above the `if word == "--"` statement and then remove the duplicate one below?

File: crates/typst-library/src/text/lorem.rs [hunk 10]
```diff
@@ -61,59 +42,64 @@ fn generate_lorem(n: usize) -> String {
...
-        sentence
-    })
+        if needs_cap {
+            // Capitalize the first character in a string.
+            let idx = match word.chars().next() {
+                Some(c) => c.len_utf8(),
+                None => 0,
+            };
+            sentence.push_str(&word[..idx].to_uppercase());
+            sentence.push_str(&word[idx..]);
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: Sorry for not noticing in the first round, but there was still an unnecessary allocation here, that can be avoided quite idiomatically:
```suggestion
            // Capitalize the first character of the word.
            if let Some(c) = word.chars().next() {
                sentence.extend(c.to_uppercase());
                sentence.push_str(&word[c.len_utf8()..]);
            }
```

File: crates/typst-library/src/text/lorem.rs [hunk 11]
```diff
@@ -20,5 +24,82 @@ pub fn lorem(
...
     words: usize,
 ) -> Str {
-    lipsum::lipsum(words).replace("--", "–").into()
+    generate_lorem(words).into()
+}
+
+// Ported from https://github.com/mgeisler/lipsum/blob/0.9.1/src/lib.rs
+// MIT License
+// Copyright (c) 2017 Martin Geisler
+// See NOTICE for full attribution.
```
Comment (saecki) [inline crates/typst-library/src/text/lorem.rs]: This is just personal preference, but I think the comment looks a bit odd above the doc comment. Could you move it as the first thing inside the function?

**Review by saecki — APPROVED** [review]

**Comment by laurmaedje** [comment]
Thanks!
